### ISSUE TITLE
Say what particular C function is being sampled

### ISSUE THREAD

**Issue by segiddins** [rbspy/rbspy#110]
I _think_ this should be possible, at worst by reading the instruction pointer and walking back until you find a function?

This would be very helpful for me, since apparently I'm spending 60% of time in unknown C functions.

**Comment by jvns** [comment]
Yeah, I think I might give this a shot! Can you send me a flamegraph of what you're seeing? i'd be curious to see what it looks like.

**Comment by segiddins** [comment]
Uploaded the flamegraph, but the 60% number comes from the summary that you print out while sampling
[rbspy-2018-02-21-w6gzSFp10X.flamegraph.svg.zip](https://github.com/rbspy/rbspy/files/1749219/rbspy-2018-02-21-w6gzSFp10X.flamegraph.svg.zip)

**Comment by jvns** [comment]
thanks! I think what's going on in your case (and this is likely to be true for a lot of people) is that there are a lot of different C functions being called, but they're all aggregated together and so it looks weird.

I wonder if (as a start) it would make sense to just exclude C functions from the summary because it's so uninformative and instead just report whatever Ruby function is closest to the top of the stack.

**Comment by segiddins** [comment]
> I wonder if (as a start) it would make sense to just exclude C functions from the summary because it's so uninformative and instead just report whatever Ruby function is closest to the top of the stack.

I think that would be much more helpful!

**Comment by AlexWayfer** [comment]
I tried `rbspy` with [`puma`](https://github.com/puma/puma) and there is:

```
% self  % total  name
 99.68   100.00  <c function> - unknown
...
```

:disappointed_relieved:

**Comment by ViugiNick** [comment]
@jvns I tried to implement the logic of getting the c-level frame symbols. Actually, I just took it from .gdbynit and reimplement on rust. `VM_FRAME_TYPE($cfp->flag) == VM_FRAME_MAGIC_CFUNC` section(https://github.com/ruby/ruby/blob/d4f1187d31ee300c502713587a26ca186c8e04b9/.gdbinit#L1157) and `check_method_entry` method(https://github.com/ruby/ruby/blob/d4f1187d31ee300c502713587a26ca186c8e04b9/.gdbinit#L1053) works just fine and symbold ID obtaining successfully. But I ran into a problem when trying to get a symbol by it's ID(https://github.com/ruby/ruby/blob/d4f1187d31ee300c502713587a26ca186c8e04b9/.gdbinit#L1068). This method uses the global cache(`global_symbols`) and number of constants: tLAST_OP_ID, RUBY_ID_SCOPE_SHIFT, ID_ENTRY_UNIT, RUBY_FL_USER1, RUBY_FL_USER3, RUBY_FL_USER4, RUBY_FL_USHIFT, ID_ENTRY_SIZE and I do not really understand how to work with them. Could you please help with rb_id2name implementation.

**Comment by cataphract** [comment]
@ViugiNick Do you have a diff of your changes? Maybe I can can take a shot at it, though I don't know Rust.

**Comment by ViugiNick** [comment]
@cataphract @jvns https://gist.github.com/ViugiNick/583a55a73a515891f545e57653127def 
this code snippet finds a method entry (me) and obviously mid = me->def->original_id. But it does not work out for me to get the readable name of the method.

**Comment by x-ji** [comment]
@AlexWayfer Me too even though #114 should have ensured that C functions are ignored?

**Comment by vizcay** [comment]
I have tried to use `rbspy` to profile a Rails 6 application with ruby 2.6.2 an it is completely inusable because of this:

```
Summary of profiling data so far:
% self  % total  name
 93.14    99.97  <c function> - unknown
  0.15     0.20  [] - /usr/local/rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.92.0/lib/seahorse/model/shapes.rb
  0.12     0.23  jsonify - /usr/local/rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/json/encoding.rb
  0.12     0.20  block in normalized_querystring - /usr/local/rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/aws-sigv4-1.1.1/lib/aws-sigv4/signer.r
...
```

**Comment by ilyazub** [comment]
@vizcay Try `perf report` from [`perf` Linux profiler](http://www.brendangregg.com/perf.html) and [`flamegraph`](https://github.com/flamegraph-rs/flamegraph) crate to dig into C code. You may need to recompile C extensions with debug symbols (like `CFLAGS=-g`, it depends on the extension).

**Comment by acj** [comment]
The code still needs a bit of polish, but I have this mostly working for ruby 2.7. Details in #282. Big thanks to @ViugiNick for the tip about porting the gdbinit functions.

If anyone has time to give it a try, I'd be grateful for any feedback and testing help.

**Comment by jvns** [comment]
SO DELIGHTED that this is fixed, I really had no idea how to approach this and this was the #1 biggest feature I wanted rbspy to have the most. thanks again so much @acj!!!

**Comment by keb** [comment]
I know this is supposed to be fixed but I am experiencing something similar with the latest version of rbspy `0.15.0` on a Rails 7 app using Ruby 3.0.1. I ran `rbspy record --subprocesses -- ruby ./bin/rails s` needing to specify `ruby` since by default rbspy doesn't seem to play nicely with chruby.

Unfortunately, the profiling data and flamegraph were practically useless:
```
Summary of profiling data so far:
% self  % total  name
 97.96    97.96  select [c function] - (unknown)
  1.54     1.54  sleep [c function] - (unknown)
  0.17     0.17  pop [c function] - (unknown)
  0.07     0.07  gsub [c function] - (unknown)
  0.03     0.03  wait_readable [c function] - (unknown)
  0.03     0.03  sign [c function] - (unknown)
  0.03     0.03  printable - /home/kevin/.gem/ruby/3.0.1/gems/amazing_print-1.4.0/lib/amazing_print/inspector.rb
  0.03     0.03  prepare [c function] - (unknown)
  0.03     0.03  module_eval [c function] - (unknown)
  0.03     0.03  log - /home/kevin/.gem/ruby/3.0.1/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters
  0.03     0.03  deduplicate - /home/kevin/.gem/ruby/3.0.1/gems/activerecord-7.0.3.1/lib/active_record/connection_
  0.03     0.03  camelize - /home/kevin/.gem/ruby/3.0.1/gems/activesupport-7.0.3.1/lib/active_support/inflector/me
  0.00    97.96  select_loop - /home/kevin/.gem/ruby/3.0.1/gems/puma-5.6.5/lib/puma/reactor.rb
  0.00    97.96  block in run - /home/kevin/.gem/ruby/3.0.1/gems/puma-5.6.5/lib/puma/reactor.rb
  0.00     1.04  block in start! - /home/kevin/.gem/ruby/3.0.1/gems/puma-5.6.5/lib/puma/thread_pool.rb
  0.00     0.50  block in start - /home/kevin/.gem/ruby/3.0.1/gems/puma-5.6.5/lib/puma/plugin/tmp_restart.rb
  0.00     0.50  block (2 levels) in fire_background - /home/kevin/.gem/ruby/3.0.1/gems/puma-5.6.5/lib/puma/plugin
  0.00     0.30  with_force_shutdown - /home/kevin/.gem/ruby/3.0.1/gems/puma-5.6.5/lib/puma/thread_pool.rb
  0.00     0.30  process_client - /home/kevin/.gem/ruby/3.0.1/gems/puma-5.6.5/lib/puma/server.rb
  0.00     0.30  each [c function] - (unknown)
```

**Comment by acj** [comment]
@keb Can you open a new issue, please?
