### ISSUE TITLE
report shouldn't require root on Mac

### ISSUE THREAD

**Issue by wodin** [rbspy/rbspy#116]
Hi

I understand that root is required while actually profiling, but I suppose it shouldn't be necessary while just converting from raw format to something else?

    $ rbspy report -f callgrind -i rbspy.28107.gz -o rbspy.28107.txt
    rbspy only works as root on Mac. Try rerunning with `sudo --preserve-env !!`.
    If you run `sudo rbspy record ruby your-program.rb`, rbspy will drop privileges when running `ruby your-program.rb`. If you want the Ruby program to run as root, use `rbspy --no-drop-root`.
    Error. Causes: 
    - rbspy needs to run as root on mac

**Comment by jvns** [comment]
thanks for reporting! should be fixed now.
