### ISSUE TITLE
"rbspy -V" does not show version

### ISSUE THREAD

**Issue by thbar** [rbspy/rbspy#130]
Hello there!

I tried `rbspy-v0.2.3-x86_64-apple-darwin.tar.gz` and just wanted to verify the version. Apparently the version is not printed on screen:

```
09:02 $ rbspy --version
rbspy 
✔ ~/Downloads 
09:02 $ sudo rbspy --version
Password:
rbspy 
✔ ~/Downloads 
09:03 $ sudo rbspy -V
rbspy 
```

**Comment by jvns** [comment]
Thanks for reporting this! Fixed on master now :)

**Comment by thbar** [comment]
You welcome - thanks for the fix!

Envoyé de mon iPhone
