### ISSUE TITLE
Support Ruby 2.4.4

### ISSUE THREAD

**Issue by kirs** [rbspy/rbspy#136]
```
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.4.4. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:247:14
```

2.3.7, 2.4.4 and 2.5.1 have all been released on March 28. rbspy [already supports](https://github.com/rbspy/rbspy/commit/3b1e7b1bcc88203600759b02d14e8edb88bec7d9) 2.5.1. 

@jvns would it be easy to add support for 2.4.4 (and probably 2.3.7) as well? Thanks!

**Comment by jvns** [comment]
Thanks for reporting! I didn't realize that minor version releases to 2.3/2.4/2.5 all came out at the same time. I'll know next time!
