### ISSUE TITLE
Inaccurate flamegraph when using threads

### ISSUE THREAD

**Issue by vaneyckt** [rbspy/rbspy#138]
Hey there,

I was taking rbspy for a run and was testing how well it sampled threaded programs. My code was as follows:

```
def foo
  sleep 10
end

def bar
  sleep 10
end

threads = []
threads << Thread.new { 10.times { foo } }
threads << Thread.new { 10.times { bar } }
threads.each(&:join)
```

My expected flamegraph would show that half the time was spent in `foo` and the other half in `bar`. Unfortunately, this was the output:

![screen shot 2018-04-08 at 11 33 02](https://user-images.githubusercontent.com/767465/38466411-8b5ad5d6-3b20-11e8-8ec3-aa78b4fad242.png)

I was using `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]`. Do you know if I'm doing anything wrong here?

**Comment by liaden** [comment]
Try smaller sleeps that happen a lot more because the OS may not be
scheduling the threads to run? Alternatively, try setting the rate to use
an odd time period such as 97hz instead of 100hz. It is also worth
remembering you have a third thread that is waiting on the other two so I
wouldn't expect a 50/50 between `foo` and `bar`.

**Comment by jvns** [comment]
Here's a different threaded program, where equal amounts of time are spent between `foo` and `bar:

```
$a = 0

def foo
    100.times do
        $a += 1
    end
end

def bar
    100.times do
        $a += 1
    end
end

threads = []
threads << Thread.new { loop{ foo } }
threads << Thread.new { loop{ bar } }
threads.each(&:join)
```

```
Time since start: 20s. Press Ctrl+C to stop.
Summary of profiling data so far:
% self  % total  name
 32.21    32.21  block in foo - test.rb
 31.86    31.86  block in bar - test.rb
 17.74    49.60  bar - test.rb
 16.70    48.91  foo - test.rb
```

**Comment by jvns** [comment]
I don't believe this is an issue with rbspy, but if you believe it is then feel free to reopen!
