### ISSUE TITLE
os error 14 on Ubuntu

### ISSUE THREAD

**Issue by pixelastic** [rbspy/rbspy#145]
Hello,

I tried to use rbspy to profile a `jekyll build` call on Ubuntu 16.04, but I'm having the following error:

```
$ rbspy record -- bundle exec jekyll build
Press Ctrl+C to stop
Dropped 29/57 stack traces because of errors.
Wrote raw data to /home/tim/.cache/rbspy/records/rbspy-2018-04-30-J3YBZ0ZThp.raw.gz
Writing formatted output to /home/tim/.cache/rbspy/records/rbspy-2018-04-30-73lvDNz4eP.flamegraph.svg
Error. Causes:
- Failed to copy memory address 7fd85f24c820
- Bad address (os error 14)
```

The actual `jekyll build` command is correctly executed, though.

The repository to reproduce the error can be found here: https://github.com/algolia/jekyll-algolia-example
```
$ bundle install
$ rbspy record -- bundle exec jekyll build
```

Happy to help if there's anything I can do :)

**Comment by jvns** [comment]
Thanks for reporting this! I tried it on my computer and got [this flamegraph](https://user-images.githubusercontent.com/817739/39461458-bf16ed00-4cd8-11e8-9d86-520625d259d4.png), so I don't think it's to do with the Ruby code here.

How did you install Ruby? It would help if you could send me a core dump or two of the Ruby process's memory so I can see if I can figure out what's going on. Here's how to get a core dump:

first, start a while loop that will try to grab a core dump:
```
while true
do 
sudo gcore $(pgrep -f jekyll)
sleep 0.5
done
```

and then run `bundle exec jekyll build`

`gcore` will generate a file named like `core.24996`, which is the core dump. 

you can either upload them somewhere or email them to julia@jvns.ca.

**Comment by pixelastic** [comment]
I'm using ruby through `rvm`. Here is the output of `ruby -v`:
```
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
```

Here is the incomplete flamegraph I initially got: 
![rbspy-2018-05-02-yzldx6arj9 flamegraph](https://user-images.githubusercontent.com/283419/39516568-9a6fe620-4dfd-11e8-9605-ef4a9cd33e59.png)

And here are two dumps:
- http://tmp.pixelastic.com/share/core.19844
- http://tmp.pixelastic.com/share/core.21121

Thanks!

**Comment by pathawks** [comment]
I am getting a similar error message when I run on EC2 using `Amazon Linux AMI 2018.03.0.20180508 x86_64 HVM`


https://homepage.cs.uiowa.edu/~hawks/core.16680.zip

**Comment by pathawks** [comment]
I tried several different operating systems and machines, but could not get `rbspy` to work with RVM.

If I instead use `rbenv` it works without issue.

**Comment by wabain** [comment]
It looks like what's happening here is that RVM has some kind of hooking logic that launches a Ruby process running ruby_executable_hooks, then execv's Bundler, wiping out the address space and starting up a new instance of the interpreter. The memory address that cannot be copied is the pointer to the initial Ruby thread.

The easy workaround here is that it seems RVM does all this indirection [in service of](https://github.com/rvm/rubygems-bundler) allowing `rbspy record -- jekyll build`, which works. But more generally it would be nice if rbspy could handle execv calls. (I could imagine this coming up in programs using fork-then-execv strategies too.) I've hacked together some code that takes the naive approach of reinitializing the StackTraceGetter if the pointer to stack becomes invalid and it seems to work. Would a PR along those lines be of interest?

**Comment by jvns** [comment]
yes, a PR along those lines sounds great. Thanks for investigating this! I'd love to get rbspy working with RVM.

**Comment by neosilky** [comment]
@pixelastic #177 should have fixed your issue. Can you confirm this is the case?

**Comment by pixelastic** [comment]
Thanks for taking the time to investigate and fix this. Unfortunately I moved to other projects, stacks and environments in the meantime and can't try the fix and confirm if it's working.

I'm still going to close this, I'll re-open if I ever encounter this issue again.

Thanks for all your work
