### ISSUE TITLE
Little details in profile of rspec

### ISSUE THREAD

**Issue by zdrummond** [rbspy/rbspy#146]
I just started to use the tool the other night, and actually want to use it exactly for one of the primary use-cases "One common use case for rbspy is profiling slow unit test runs " :grinning:

However, I am getting confusing results on my first try
I ran it on a test[1] in rspec (macos 10.13.4), and I get one big lump of a flame graph

![image](https://user-images.githubusercontent.com/1627527/39451600-0a42b50c-4c84-11e8-8e6f-28ef7b65dc49.png)

There is a lot of `unknown line 0`, and for what there is for info seems unrelated (spring and require).

I am new to *nix perf, so let me know if I am just making a novice mistake and need to do something more to configure it

[1] `rbspy record -- bin/rspec <file_path`

**Comment by jvns** [comment]
Ooh, this is really interesting! My guess at what's happening here is -- Spring seems to be a Rails application preloader, and it looks like it's running some other process (maybe your Rails app?) in a function called `run_command`.

Can you try running with `rbspy record --subprocesses -- bin/rspec <file_path>` and see if it works any better? Then rbspy will also profile any Ruby subprocesses that your test suite starts up.

**Comment by liaden** [comment]
I know spork forks a new process to run tests without dirtying the original
process. I expect spring is doing the same here.

**Comment by zdrummond** [comment]
'--subprocesses flag isn't implemented on Mac OS yet, sorry!’  :(

I will try brining up a VM to run it on.

And yup Joel, Spring uses fork to preserve the rails environment

On May 1, 2018, 6:39 AM -0700, Joel Johnson <notifications@github.com>, wrote:
I know spork forks a new process to run tests without dirtying the original
process. I expect spring is doing the same here.

**Comment by jvns** [comment]
Going to close this and open a separate issue about the `--subprocesses` flag on Mac. feel free to reopen though!

**Comment by nhelvig** [comment]
I'm getting the same issue when using the profiler in RubyMine. It has a flag which supposedly supports subprocesses but the output I get is pretty much the same as the screenshot above, I only see details about spring and nothing about the code in the test I am running. Was adding support for `subprocesses` supposed to alleviate that?

**Comment by ViugiNick** [comment]
@nhelvig Could you please run something like @jvns proposed (https://github.com/rbspy/rbspy/issues/146#issuecomment-385597746) in your terminal and check if output graph will be any better

**Comment by ViugiNick** [comment]
@nhelvig or you can use `Attach profiler to process` feature (https://www.jetbrains.com/help/ruby/cpu-profiler.html#run_profiling_session) and attach to `bin/rspec <file_path>` process
