### ISSUE TITLE
Can't run `rails s` with rbspy

### ISSUE THREAD

**Issue by keoghpe** [rbspy/rbspy#157]
I was wondering if it would be possible to see every method call inside my rails app from the moment I run `rails s`. I tried running `sudo rbspy record rails s` but the server wont run. I've tried a few different variations `bundle exec rails s`, `bin/rails s` etc but these don't work either. 

**RVM Version:** rvm 1.29.3
**Ruby Versions:** 
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
(I've tried in two different apps, both of which work fine with regular rails commands)
**Rails version:** 5.2

Here's the output I get:

```
my_project ➤ sudo rbspy record rails s                                                                                                                                 git:master
Dropping permissions: running Ruby command as user keoghpe
Press Ctrl+C to stop
thread '<unnamed>' panicked at 'Couldn't find __mh_execute_header symbol', libcore/option.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Wrote raw data to /Users/keoghpe/.cache/rbspy/records/rbspy-2018-06-24-2BbKatsxSI.raw.gz
Writing formatted output to /Users/keoghpe/.cache/rbspy/records/rbspy-2018-06-24-3pTLLjl6wj.flamegraph.svg
ERROR: No stack counts found
my_project ➤ Could not find proper version of railties (5.2.0) in any of the sources                                                                                   git:master
Run `bundle install` to install missing gems.
```

I'm happy to provide any additional info to help debug this or look into this further myself if people can point me in the right direction.

P.S. Thanks for creating this awesome program! 😄

**Comment by tvanderpol** [comment]
Based on the error (can't find `railties` gem) I suspect this has something to do with rvm and your path when sudoing.

To exclude any bundler shenanigans can you try `sudo rbspy record bundle exec rails s`. I think rails is supposed to have something built in to automatically invoke bundler but it seems a good thing to exclude.

Next thing to try would be sudo bundle install - if it installs a whole raft of gems again it'd suggest that your account when sudoed looks different to rvm than without sudo. 

Two additional data points:

- I use `rbenv` for ruby version management and `sudo rbspy record bundle exec rails s` works like you'd expect.
- When you forget `sudo`, rbspy reminds you "rbspy only works as root on Mac. Try rerunning with `sudo --preserve-env !!`." - it might be worth trying that flag? (from my admittedly hazy memory RVM definitely uses some environment stuff to keep it's work straight)

**Comment by gnclmorais** [comment]
I gave it a try on my macOS (`sudo rbspy record bin/rails s`) and it worked… 🤔 A few of my specs:
- `macOS High Sierra 10.13.6`
- `rbenv 1.1.1`
- `ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]`
-  `Rails 5.0.6`

@keoghpe, do you use rbenv or something similar?

**Comment by sivalingams** [comment]
```
$ sudo rbspy record rails s
Dropping permissions: running Ruby command as user sivalingams
Press Ctrl+C to stop
/Users/sivalingam/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem railties (>= 0.a) with executable rails (Gem::GemNotFoundException)
	from /Users/sivalingam/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems.rb:308:in `activate_bin_path'
	from /Users/sivalingam/.rvm/gems/ruby-2.3.7/bin/rails:23:in `<main>'
	from /Users/sivalingam/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `eval'
	from /Users/sivalingam/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `<main>'
Wrote raw data to /Users/sivalingam/.cache/rbspy/records/rbspy-2019-07-17-J7qjS4MZmc.raw.gz
Writing formatted output to /Users/sivalingam/.cache/rbspy/records/rbspy-2019-07-17-PWKs0nsx8B.flamegraph.svg
```

- macOS Mojave 10.14.5
- ruby 2.3.7 (2018-03-28) [x86_64-darwin18]
- Rails 3.2.22.5
- rvm 1.29.7 (latest)

**Comment by tvanderpol** [comment]
Use the binstub (so `sudo rbspy record bin/rails s` in your application directory`) or explicitly wrap it in a bundler call: `sudo rbspy bundle exec rails s`. If that fails the problem will likely be that when you run some ruby code as sudo it doesn't have access to the same installed gems as when run as user. Either way this isn't a rbspy specific problem.

**Comment by acj** [comment]
It looks like we have good workarounds for this, and it may be fixed in a recent version of rbspy. Feel free to reopen this if it's still an issue.
