### ISSUE TITLE
Support Ruby 2.6.x

### ISSUE THREAD

**Issue by DirtyF** [rbspy/rbspy#159]
👋 

For the record here's the error message you get when using 💎 **ruby 2.6.0preview2** (2018-05-31 trunk 63539) [x86_64-darwin17] on macOS:

```thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.6.0. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:251:14```

Thanks for this great tool 🔥 😍

**Comment by jvns** [comment]
Addressing this is actually going to be somewhat complicated because Ruby 2.6 introduces a JIT. I haven't spent any time looking at this yet, but I'd like to!

**Comment by joevandyk** [comment]
@jvns I don't know a lot about the 2.6 JIT - but I think it's possible to run with it disabled, and I think it's disabled by default? 

I'm running into the 2.6.1 not being supported error.

**Comment by jvns** [comment]
oh, if the JIT is disabled by default then it definitely shouldn't be an
issue. I'll take a look!

**Comment by ioquatix** [comment]
I love `rbspy` can I help to make it work with 2.6.x?

**Comment by seanlinsley** [comment]
I haven't used `rbspy` before but ran into this issue, and would also be happy to help.

**Comment by kzys** [comment]
Yes. Ruby 2.6's JIT compiler (MJIT) is still experimental and enabled by default.

https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/

> In order to enable the JIT compiler, specify --jit on the command line or in the $RUBYOPT environment variable. 

We still need to port Ruby's structs (rb_thread_struct?) to rbspy, but it shouldn't be rocket-science hard.

**Comment by neosilky** [comment]
I'm pretty sure I managed to get 2.6.x working with `rbspy` a couple of months ago, but I can't find the code. I will have another bash at it...

**Comment by neosilky** [comment]
Ok, I think I have 2.5.4, 2.5.5, 2.6.0, 2.6.1, 2.6.2 and 2.6.3 working.

I'm just seeing some weird behavior with the line numbering that also seems to be present in the current version. It's not critical so I'll probably just push so people can get it running

**Comment by mikedalpee** [comment]
Any idea when you will push this?  Would really love to get something going with 2.6.3.  Thanks.

**Comment by neosilky** [comment]
@mikedalpee Just pushed! As I said, line numbers are a little broken but you should be able to use it anyway :grinning:

**Comment by mikedalpee** [comment]
I cloned https://github.com/neosilky/rbspy/tree/ruby-support, built it, and ran the tests, but 
got the following output:

```
running 22 tests
test core::initialize::test_get_disallowed_process ... ok
test core::initialize::test_get_nonexistent_process ... ok
test ui::callgrind::tests::stats_aggregate ... ok
test tests::test_report_arg_parsing ... ok
test ui::descendents::test_get_descendents ... ok
test ui::descendents::test_get_descendents_depth_2 ... ok
test ui::callgrind::tests::stats_write ... ok
test ui::descendents::test_status_file_ppid ... ok
test test_output_filename ... ok
test ui::summary::tests::stats_by_function ... ok
test ui::summary::tests::stats_by_line_number ... ok
test ui::flamegraph::tests::test_stats ... ok
test tests::test_arg_parsing ... ok
test core::initialize::test_current_thread_address ... FAILED
test core::initialize::test_get_trace ... FAILED
test ui::flamegraph::test_write_flamegraph ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_1_9_3 ... ok
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.6.3. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:254:14
test core::ruby_version::tests::test_get_ruby_stack_trace_2_5_0 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_4_0 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_1_6 ... ok
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.6.3. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:254:14
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.6.3. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:254:14
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.6.3. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:254:14
test core::ruby_version::tests::test_get_ruby_stack_trace_2_1_6_2 ... ok
test test_spawn_record_children_subprocesses ... test test_spawn_record_children_subprocesses has been running for over 60 seconds
```
After which the test suite appears to be hung.

**Comment by mikedalpee** [comment]
@neosilky Is there anything special I should do when running this?  In particular, does it work with JIT enabled?

**Comment by neosilky** [comment]
@mikedalpee You should just be able to run it out of the box.

I honestly don't know if it'll work with the JIT, I haven't had time to test that. I would suspect some weird stuff goes on though.
