### ISSUE TITLE
Include sample timestamps in file format

### ISSUE THREAD

**Issue by jlfwong** [rbspy/rbspy#162]
In #161, I'm adding support for visualizing program execution into speedscope. Speescope supports display using units, but from the file format alone, I can't tell what the sampling frequency was, so I can't display time accurately on axes.

If the file format included the sampling frequency, that would unlock better display of profiles.

**Comment by jvns** [comment]
I'd accept a contribution that did this!

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I ran into this as well. Specifically, I was looking at the possibility of converting an rbspy profile to pprof (for upload to [cloud profiler](https://cloud.google.com/profiler/)) and/or [nflxprofile](https://github.com/Netflix/nflxprofile) for use with [flamescope](https://github.com/Netflix/flamescope).
