### ISSUE TITLE
Support installing with homebrew

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#163]

**Comment by jeremyjung** [comment]
Hi @jvns. I'm happy to take this, but I noticed the cargo.toml version for v0.3.1 installs as v0.2.10 which may confuse homebrew users.  Should I go ahead and submit the v0.2.10 release or would you like me to wait for a new version?

**Comment by jvns** [comment]
I made a v0.3.2 version which will install as 0.3.2. having somebody to help this would be GREAT, thank you so much!

**Comment by jeremyjung** [comment]
I just pulled the 0.3.2 version and it looks like it's missing the commit that changes the cargo.toml (https://github.com/rbspy/rbspy/compare/v0.3.2...master).  Maybe the release needs to be repushed?

**Comment by jvns** [comment]
Fixed!

**Comment by jeremyjung** [comment]
PR was just merged, thanks for the help!

https://github.com/Homebrew/homebrew-core/pull/31533

**Comment by jvns** [comment]
Thank you so much! This is really exciting. I'll update the README!
