### ISSUE TITLE
Make AppVeyor CI push Windows binaries to releases page

### ISSUE THREAD

**Issue by DAMisener** [rbspy/rbspy#171]
There is talk of Windows support but I can't seem to source a binary.

**Comment by jvns** [comment]
You can find a binary here. We need to get appveyor to push the binaries to the releases page though. https://ci.appveyor.com/project/jvns/rbspy/build/1.0.14/artifacts

**Comment by ashmaroli** [comment]
> We need to get appveyor to push the binaries to the releases page

Helpful link for those preparing a PR for this:
https://www.appveyor.com/docs/deployment/github/

**Comment by janpio** [comment]
For context, this is how releases are published from Travis:
https://github.com/rbspy/rbspy/blob/1a813083f152a7bdddbdb5c21ee6e52941959b6c/.travis.yml#L59-L85

(Note the regex at the end so tags are also built, not just `master`)

Example run on Travis for a tag: https://travis-ci.org/rbspy/rbspy/builds/421378669?utm_source=github_status&utm_medium=notification

**Comment by janpio** [comment]
Recent builds create two `rbspy.exe`: https://ci.appveyor.com/project/jvns/rbspy/build/1.0.31 - one for x86_64, one for i686 - 32bit vs 64bit I guess. How could this be represented on the releases page?

**Comment by acj** [comment]
Our regular CI builds are now publishing Windows build artifacts (#297). I'll make sure that we attach them to new releases as part of #293.
