### ISSUE TITLE
Memory allocation profiling?

### ISSUE THREAD

**Issue by hartator** [rbspy/rbspy#181]
I love rbspy, thanks so much for the amazing work, it has been so easy to find optimization in our code. 

I wonder if it's possible to use rbspy to do the same thing that it does for CPU usage, but for RAM usage? Or do you know another tool in the same vein?

We've a memory leak in our application, and wasn't able to find it. Right now we're killing our Puma workers every 5 minutes, doesn't seem very optimal lol.

**Comment by DanielHeath** [comment]
Seems unlikely to end up being part of `rbspy` as there would be ~no common code.

You probably want https://github.com/SamSaffron/memory_profiler .

**Comment by liaden** [comment]
Could use https://docs.ruby-lang.org/en/2.5.0/dtrace_probes_rdoc.html#label-Declared+probes for tracing ruby objects, but if it is an issue with a memory leak in a C gem, this won't help much. Also, it is nice to see https://github.com/dalehamel/ruby-static-tracing exists.

**Comment by acj** [comment]
Closing since a few good alternatives have been mentioned, and it's unlikely that we'll add memory profiling to rbspy. Thanks, all.
