### ISSUE TITLE
[Windows] `rbspy record -- bundle exec fastlane -v` fails with `Error. Causes: - The system cannot find the file specified. (os error 2)` 

### ISSUE THREAD

**Issue by janpio** [rbspy/rbspy#183]
I am on Windows 10, newest update. Ruby is `ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]` installed in `C:\Ruby24-x64`/`C:\Ruby24-x64\bin` (from rubyinstaller.org).

I "installed" rbspy by copying the three build artifacts from https://ci.appveyor.com/project/jvns/rbspy/build/1.0.18/artifacts to `C:\Ruby24-x64\bin`.

---

I have a local checkout of https://github.com/fastlane/fastlane that I can run via `bundle exec`:

```
λ bundle exec fastlane -v
fastlane installation at path:
C:/Projects/Fastlane/win-fastlane/bin/fastlane
-----------------------------
[✔] 🚀
fastlane 2.105.2
```

Now when I try to use `rbspy` on it, I get this nice error message:

```
λ rbspy record -- bundle exec fastlane -v
Error. Causes:
- The system cannot find the file specified. (os error 2)
```

(I can use `rbspy` on `ruby file.rb`)

**Comment by janpio** [comment]
Found https://github.com/rbspy/rbspy/issues/175 and following the instruction in there right now.

**Comment by janpio** [comment]
Installing the most recent build from https://ci.appveyor.com/project/jvns/rbspy/build/1.0.31/job/brmcjokwa7hmsw6c/artifacts didn't change anything.

**Comment by benfred** [comment]
@janpio We don't follow subprocesses on windows yet, so passing a .bat file as the command line to run won't work (since ruby will be running as a child process of the bat file)

You'll need to either launch  ```C:\Ruby24-x64\bin\bundle.bat exec fastlane -v``` separately and then pass the pid of the ruby process to rbspy ```(rbspy record --pid <pid_of_ruby_subprocess>``` or you will need to invoke ruby directly  by doing something like ```rbspy record ruby c:\Ruby24-x64\bin\bundle exec fastlane -v```

**Comment by janpio** [comment]
> You'll need to either launch C:\Ruby24-x64\bin\bundle.bat exec fastlane -v separately and then pass the pid of the ruby process to rbspy (rbspy record --pid <pid_of_ruby_subprocess>) ...

This will probably not work as the process is a rather short one.  
I'd also prefer to know what the whole process run is doing. That won't work then, right?

> ... or you will need to invoke ruby directly by doing something like `rbspy record ruby c:\Ruby24-x64\bin\bundle exec fastlane -v`

That actually seemed to work, although only on the second try. First one unfortunately is lost to me typing `clear` before trying again, but here is the output of the second one:

```
λ rbspy record -- ruby c:\Ruby24-x64\bin\bundle exec fastlane -v
```
(Note the `--` so that `-v` can atually work at the end of the command)

Then the whole terminal content is deleted and replaced with:

```
Time since start: 7s. Press Ctrl+C to stop.
Summary of profiling data so far:
% self  % total  name
100.00   100.00  <c function> - unknown
  0.00    98.44  <main> - c:/Ruby24-x64/bin/bundle
  0.00    98.30  <top (required)> - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/exe/bundle
  0.00    94.60  with_friendly_errors - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb
  0.00    94.60  block in <top (required)> - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/exe/bundle
  0.00    94.18  start - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb
  0.00    94.18  start - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb
  0.00    94.18  dispatch - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb
  0.00    94.18  dispatch - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb
  0.00    94.03  run - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb
  0.00    94.03  run - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb
  0.00    94.03  invoke_command - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb
  0.00    94.03  exec - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb
  0.00    93.89  kernel_exec - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb
  0.00     4.55  require - C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb
  0.00     2.13  <top (required)> - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb
  0.00     1.85  <top (required)> - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendored_thor.rb
  0.00     1.85  <top (required)> - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb
  0.00     1.70  <top (required)> - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb
  0.00     1.56  <top (required)> - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler.rb
fastlane 2.105.2
Wrote raw data to C:\Users\Jan\.cache\rbspy\records\rbspy-2018-09-25-F2k8KdZYb5.raw.gz
Writing formatted output to C:\Users\Jan\.cache\rbspy\records\rbspy-2018-09-25-5W9rcg0Eot.flamegraph.svg
```

The flamegraph looks real, and the `.gz` has a `.raw` with useful (?) content.
[rbspy-2018-09-25-gFd9xCwAWo.raw.txt](https://github.com/rbspy/rbspy/files/2416377/rbspy-2018-09-25-gFd9xCwAWo.raw.txt)

**Comment by benfred** [comment]
awesome! glad it's working out for you.

The terminal output will look nicer soon on windows, I have a version that works better on windows here http://github.com/benfred/py-spy/ and I'm planning on [moving this code to a common crate](https://github.com/rbspy/rbspy/issues/180) so that rbspy/py-spy can both use it.

**Comment by janpio** [comment]
Ok, now I know a bit more about flamegraphs I see that the one being generated here is just for the `bundle exec` internals, nothing about the actual `fastlane`.

![image](https://user-images.githubusercontent.com/183673/46046884-0499bb00-c123-11e8-8485-51b5ae9549f6.png)

Bug or feature?
Related or unrelated to me being on Windows?

**Comment by benfred** [comment]
It looks like most of the time is spent in a 'kernel.exec' call : https://github.com/bundler/bundler/blob/master/lib/bundler/cli/exec.rb#L53 

This launches a subprocess - and rbspy doesn't attach to subprocesses on windows yet =(. If you can get the commandline of the process being launched you could try profiling that instead.  It might even be as simple as something like```rbspy record -- ruby c:\Ruby24-x64\bin\fastlane -v```

**Comment by janpio** [comment]
Unfortunately not as `bin/fastlane` is the global fastlane installed via `gem install ...`. That why I was trying `bundle exec fastlane`, which uses whatever is defined in the `Gemfile` (which then points to my local checkout where I can make modifications).
