### ISSUE TITLE
Flamegraphs/Icicle Graphs with 100% width?

### ISSUE THREAD

**Issue by janpio** [rbspy/rbspy#186]
I have this nice wide monitor, but the graphs seem to only use 1200px by default. Is there a way to change this?

**Comment by jvns** [comment]
We could add a `--flamegraph-width` option if you're interested in implementing it! flamegraph.pl does support a `--width` argument https://github.com/brendangregg/FlameGraph/blob/master/flamegraph.pl#L135

**Comment by janpio** [comment]
Ah, this is also where the default comes from 🥇 

I'm not sure if adding a new option to each command just to configure this would be useful.

Does `rbspy` have a configuration file where such things could be "persisted"?

**Comment by janpio** [comment]
Is this something you would consider to make such "fringe" options more usable or do you not see the need for it (yet)? (I personally am undecided.)

Maybe we better add a `--flamegraph` option that can be used to configure all/more options of the flamegraph.pl script?
