### ISSUE TITLE
Coloring flamegraphs?

### ISSUE THREAD

**Issue by janpio** [rbspy/rbspy#187]
Flamegraphs are a new thing that `rbspy` introduced for me, so please bear with me 🐻 :

> The colours are randomly generated (they don’t mean anything)

From: https://rbspy.github.io/using-flamegraphs/

After looking at my first flamegraphs/Icicle graphs generated with `rbspy` it would totally make sense to be able to color the individual rectangles based on e.g. the path of the file (my gem vs. all other gems), type (ruby core vs. userland code) and similar.

Does this exist?

**Comment by janpio** [comment]
After watching http://www.brendangregg.com/flamegraphs.html#Presentation I see this is actually available at the version Netflix is using / he is presenting (separating Java, Kernel and other code into different colors). That would be neat.

**Comment by jvns** [comment]
I don't believe the flamegraphs.pl script supports custom coloring schemes but this is a cool idea! Would totally merge a PR if someone figures out how to do it :)

**Comment by janpio** [comment]
Looked into this a tiny bit:

flamegraphs.pl does have `colors` and `hash` options:
```
--colors      # set color palette. choices are: hot (default), mem, io,
              # wakeup, chain, java, js, perl, red, green, blue, aqua,
              # yellow, purple, orange
--hash        # colors are keyed by function name hash
```
https://github.com/brendangregg/FlameGraph#options

This indicates to me that one might indeed be able to somehow use the hash function to decide which color is to be used to display a node. Maybe this could be used to achieve what I suggested above.

**Comment by liaden** [comment]
Since rbspy recognizes c functions now, I think mixed mode would have the most benefit for different colors.
