### ISSUE TITLE
Include current sample rate when rbspy fails to sample at that rate

### ISSUE THREAD

**Issue by janpio** [rbspy/rbspy#188]
What does that mean exactly?
Is this a nice tip to get a little bit better results, or are my current results total crap and only using this will give me something useful?

**Comment by janpio** [comment]
I should have mentioned that: Whatever the default is. I didn't configure a thing, then got this scary output.

**Comment by jvns** [comment]
re "what does this message mean"  -- if the percentage is low (like 3.6%), you don't have to worry and the results are fine.

**Comment by jvns** [comment]
The error message:

> "3.6% (151/4217) of stack traces were sampled late because we couldn't sample at expected rate, results may be inaccurate. Try sampling at a lower rate with `--rate`."

should include the current sample rate.

**Comment by jvns** [comment]
Tagging this as "good first issue" because including the sample rate in this error message should be really easy :)
