### ISSUE TITLE
Figure out how to load debug symbols that aren't in the binary

### ISSUE THREAD

**Issue by kamalmarhubi** [rbspy/rbspy#19]
Lots of package managers have separate packages for debug symbols. Instead of requiring people to use Ruby binaries with debug symbols embedded, it would be nice if we could just require they have the debug symbols package installed.

**Comment by jvns** [comment]
note: this issue is less important than it was (since we've moved away from using DWARF), but will still be useful.

**Comment by luser** [comment]
If you come back around to needing this I've been doing a little work on the [`moria`](https://github.com/gimli-rs/moria) crate which is intended to serve this purpose! I only have an implementation for Mac currently, but you can see [an example of it in use](https://github.com/luser/rust-disasm/blob/0758b8ac2820cd73137284423b7dfaf04c2701bd/src/lib.rs#L76) in my rust-disasm tool.
