### ISSUE TITLE
panicked at 'Ruby version not supported yet: 2.5.3. Please create a GitHub issue and we'll fix it!'

### ISSUE THREAD

**Issue by kirs** [rbspy/rbspy#192]
It would be awesome to have rbspy supporting ruby 2.5.3 that was released last week. Thanks in advance and sorry if this issue is already tracked somewhere else.

**Comment by hartator** [comment]
Thanks for the awesome work you guys are doing on this btw. I am in love with this tool. <3

**Comment by neosilky** [comment]
This was added in November so it should be OK to close.
