### ISSUE TITLE
Function not implemented (os error 38)

### ISSUE THREAD

**Issue by dustMason** [rbspy/rbspy#196]
I'm trying to use rbspy to record a process on a linux host (kernel 4.14.35). The process is a puma worker running a rails app. Its running in a docker container with the `SYS_PTRACE` capability enabled.

When I invoke `sudo ./rbspy record --format=summary --pid=$pid` I get 

```
Press Ctrl+C to stop
Wrote raw data to /root/.cache/rbspy/records/rbspy-2018-11-09-fVDwaLHJV5.raw.gz
Writing formatted output to /root/.cache/rbspy/records/rbspy-2018-11-09-hi93PXdZTo.summary.txt
Error. Causes:
- Couldn't determine Ruby version
- Couldn't create process handle for PID
- Failed to copy memory address 55e1929114bb
- Function not implemented (os error 38)
```

I'm ssh'd into the host and have root privs on the box. Any pointers on what to try next?

Thanks!

**Comment by benfred** [comment]
I realize I'm a little late to this - but what OS is the host running?

There is a similar report here: https://github.com/benfred/py-spy/issues/22 and people seem to be having issues with either Alpine linux on the host or BSD.

**Comment by benfred** [comment]
This is probably because the kernel is built without CONFIG_CROSS_MEMORY_ATTACH support : https://github.com/benfred/py-spy/issues/22#issuecomment-521687991 - meaning that the process_vm_readv call isn't available.
