### ISSUE TITLE
Add support for Ruby 2.4.6

### ISSUE THREAD

**Issue by kevinkirkup** [rbspy/rbspy#216]
With v0.3.5 Under Ubuntu 18.04:

> thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.4.6. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:254:14

**Comment by neosilky** [comment]
Will get this added!

**Comment by neosilky** [comment]
Released in v0.3.7!
