### ISSUE TITLE
Support for Ruby 2.5.3

### ISSUE THREAD

**Issue by anth1y** [rbspy/rbspy#225]
While trying to profile a rake test we found out that 2.5.3 is not supported yet...
```
bash-4.3# rbspy record --pid 5988
Press Ctrl+C to stop
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.5.3. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:251:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Wrote raw data to /root/.cache/rbspy/records/rbspy-2019-08-28-oToBaKVuhF.raw.gz
Writing formatted output to /root/.cache/rbspy/records/rbspy-2019-08-28-2wZEb0hRbi.flamegraph.svg
ERROR: No stack counts found
```

I love this tool thank you all for working so hard on this.

**Comment by daniellockyer** [comment]
Hi @anth1y!

What version of `rbspy` are you using? The latest - [0.3.7](https://github.com/rbspy/rbspy/releases/tag/v0.3.7) - supports 2.5.3. You can download it from that page, or build it yourself.

**Comment by anth1y** [comment]
yeah thanks for that I think our version we have installed is pretty old.

**Comment by daniellockyer** [comment]
I'll close this and I'll get a new version released to Cargo. :)
