### ISSUE TITLE
Support for ruby 2.5.6

### ISSUE THREAD

**Issue by khosrow** [rbspy/rbspy#228]
In trying to run `rbspy` against a Ruby 2.5.6 application, I get the following error:

```
thread 'main' panicked at 'Ruby version not supported yet: 2.5.6. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:333:14
```

Is the process of adding support for a new Ruby version straight-forward? Wondering if there's a doc about it somewhere, so new comers like me could contribute as well.

ps. Thank you for creating this wonderful tool!

**Comment by daniellockyer** [comment]
@khosrow Adding in support with #229.

Good point about the documentation for adding support. Will see what I can do.
