### ISSUE TITLE
Ruby version not supported yet: 2.6.5

### ISSUE THREAD

**Issue by da2x** [rbspy/rbspy#237]
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.6.5. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:333:14

**Comment by daniellockyer** [comment]
There is support for this in `master` but a new version is yet to be released. :)

**Comment by peterdenham** [comment]
@da2x latest version of rbspy supports 2.6.5

(`brew upgrade rbspy` on mac)

**Comment by jvns** [comment]
Fixed in #256
