### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by liaden** [rbspy/rbspy#242]
Running currently with `rbspy record --rate 400 --duration 60 --pid`, I am seeing cpu usage on htop from 8%-25% with it typically being closer to 10-18%. At one point, it did hit upwards of 75%.

**Comment by acj** [comment]
I know this was a while ago, but was the CPU usage higher than you were expecting? (75% does seem very high, but not sure about the other numbers.)

~15% is what I tend to see at this sampling rate. I'd like to do some profiling soon to see where we're spending time, as I have no idea whether we're being wasteful. Would be nice to automatically benchmark this somehow.

**Comment by acj** [comment]
Closing for now. Feel free to reopen this if rbspy's CPU usage seems too high.

**Comment by doudou** [comment]
I believe I have something ...

Without rbspy running, my code is using 18% CPU.

Attaching rbspy, I have
- 75% CPU (of one core) for my program
- 60% CPU (of one core) for rbspy
- rbspy reporting 85% of stack traces being taken late

And that's with the default sampling rate of 99. rbspy version 0.33, ruby 2.7
