### ISSUE TITLE
Enable and disable profiling from Ruby program

### ISSUE THREAD

**Issue by brunsa2** [rbspy/rbspy#247]
To help isolate program segments for profiling, it would be helpful to be able to start and stop profiling from within the Ruby program (such as pausing and resuming profiling in ruby-prof).

**Comment by jvns** [comment]
That makes a lot of sense! If you want to do this you should probably use [stackprof](https://github.com/tmm1/stackprof) (which is designed to let you choose which specific sections of your code to profile in Ruby). The whole idea of rbspy is kind of that you don't have access to the program's code and just want to treat the Ruby program as a black box.

**Comment by brunsa2** [comment]
Thank you for recommending that one (I'm in a situation where an instrumenting profiler is way to slow to capture a broad swath of a long running test while also ignoring a much larger Rails boot time). I was hoping to use this profiler since there is RubyMine support, but I'll take a look at that one, too.

**Comment by jvns** [comment]
yep, stackprof is a sampling profiler (like rbspy). I'll definitely take a look at that PR though, happy to merge something like this if it would help you :).

**Comment by brunsa2** [comment]
I just noticed this is still open. I've been using stackprof instead. Are you still interested in adding this here; if so, I can tune it up as needed for the year delay, but otherwise I no longer need it and it can be closed.

**Comment by acj** [comment]
Hi, sorry for the delay. I'm going to close this since we haven't had any more requests for the feature. The approach in your PR is nice and simple, though, so we'll keep it in mind if we need pause/resume support later on. Thanks!
