### ISSUE TITLE
Update speedscope output to include unit & timestamp

### ISSUE THREAD

**Issue by jlfwong** [rbspy/rbspy#252]
Thanks to @igorwwwwwwwwwwwwwwwwwwww's work in #250, timestamps are now included in profiles! This means that profiles exported to speedscope can be more accurate and include units to make the profiles easier to understand.

I think the relevant changes needed are to change these two lines:
 https://github.com/rbspy/rbspy/blob/5bfe998f5ecfe5929ea9b5494aa340b5ea49b09e/src/ui/speedscope.rs#L114

https://github.com/rbspy/rbspy/blob/5bfe998f5ecfe5929ea9b5494aa340b5ea49b09e/src/ui/speedscope.rs#L121 

I'm not sure when I'll get around to doing this since I don't work in ruby very often, but if someone is excited about this, I'm happy to answer any questions about speedscope, and I don't think it would be a very challenging change to make.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I'm assuming this weight is going to be the delta between samples.

That means it may be tricky to assign the weight for the first sample. I suppose we could effectively drop it by assigning a weight of 0.

Though with https://github.com/rbspy/rbspy/pull/251 we could get a baseline estimate for the first sample from the sample rate.
