### ISSUE TITLE
Can't get it  to run on windows 10

### ISSUE THREAD

**Issue by rajeee** [rbspy/rbspy#255]
Tested with both Ruby 2.2.4 and 2.6.6

`rbspy record --file=rbspy_out --format=summary -- ruby my_ruby.rb
`

> Results in:
> Wrote raw data to C:\Users\rajen\.cache\rbspy\records\rbspy-2020-04-15-Mt6AZsmliG.raw.gz
> Writing formatted output to rbspy_out
> Error. Causes:
> - Couldn't determine Ruby version
> - Couldn't create process handle for PID
> - Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
> 

The output is mostly empty.

If the default flamegraph output format is chosen, it gives:

`rbspy record --file=rbspy_out -- C:\Ruby26-x64\bin\ruby.exe my_ruby.rb
`

> Wrote raw data to C:\Users\rajen\.cache\rbspy\records\rbspy-2020-04-15-etImis6yNz.raw.gz
> Writing formatted output to rbspy_out
> [2020-04-15T09:30:55Z ERROR inferno::flamegraph] No stack counts found
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src\ui\flamegraph.rs:38:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by acj** [comment]
Hi, thanks for the report. We've fixed a lot of bugs recently that may have been causing this. I've been testing quite a bit on Windows 10 and haven't seen this error. I'm going to close this issue, but please feel free to reopen it if you're still having trouble.
