### ISSUE TITLE
Support for Ruby 2.5.8

### ISSUE THREAD

**Issue by oliverrauscher** [rbspy/rbspy#257]
This is really a great tool!

Would you consider supporting Ruby 2.5.8 as well? Unfortunately, our project is currently fixated on 2.5.x, so we want to use the latest Ruby 2.5.8.

Thanks a lot!

**Comment by donoghuc** [comment]
Are there docs somewhere describing how to support a ruby version? I see PRs like https://github.com/rbspy/rbspy/pull/249 that appear to be from community. Is the process roughly to just copy from previous update and see if anything breaks? I would also like to see 2.5.8.

**Comment by donoghuc** [comment]
Resolved with https://github.com/rbspy/rbspy/pull/261
