### ISSUE TITLE
Linux binary for 0.3.8 is an OSX executable

### ISSUE THREAD

**Issue by nbrookie** [rbspy/rbspy#260]
Hi there, 

Noticed that the Linux binary for the latest release (0.3.8) of rbspy is an OSX executable. I have confirmed that the Linux binary for 0.3.7 is indeed a Linux executable. Any chance y'all could update? Thank you!

0.3.8
```
$ curl -L https://github.com/rbspy/rbspy/releases/download/v0.3.8/rbspy-v0.3.8-x86_64-apple-darwin.tar.gz --output rbspy.tar.gz
$ tar -xvzf rbspy.tar.gz
$ file rbspy
rbspy: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```

0.3.7
```
$ curl -L https://github.com/rbspy/rbspy/releases/download/v0.3.7/rbspy-v0.3.7-x86_64-unknown-linux-musl.tar.gz --output rbspy.tar.gz
$ tar -xvzf rbspy.tar.gz 
$ file rbspy
rbspy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by jvns** [comment]
wow, that's extremely strange -- it's supposed to get uploaded automatically by the CI. I'll try again and see if it happens again.

**Comment by jvns** [comment]
I double checked and it looks like the Linux tarball contains a Linux binary -- are you sure you downloaded the right version? your curl snippet says `https://github.com/rbspy/rbspy/releases/download/v0.3.8/rbspy-v0.3.8-x86_64-apple-darwin.tar.gz` which is the OS X version

**Comment by nbrookie** [comment]
Oh man, totally got hit by a copy pasta fail. False alarm, closing this issue 😊 ...and thank you!
