### ISSUE TITLE
spontaneous exits?

### ISSUE THREAD

**Issue by doriantaylor** [rbspy/rbspy#263]
I've seen a few bug reports about `rbspy` exiting spontaneously. I'm adding to these with a report of `rbspy record` exiting on its own after a few seconds (with `$? == 0`); unlike the other reports there's no warning or error message. I'm using a version of `rbspy` I just compiled from `master` against `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]` from homebrew on macOS 10.15.5.

**Comment by jvns** [comment]
Do you have any ideas for how to reproduce? Unfortunately without steps to reproduce I can't do much.

If you're interested in hacking on the problem and trying to track down what's going on in the code yourself I'd really love the help -- I bet it's possible to make some progress with just some print statements. happy to give pointers about where to start or answer questions too -- there's a description of rbspy's architecture in the repo as well that might be helpful.

**Comment by doriantaylor** [comment]
Other than running it against some proprietary employer code I don't know how I would; I can try to create something standalone and see if it reproduces but that'll be a few weeks before I have an opening for something like that.

It (ostensibly) doesn't crash or anything, it just…quits. I'm assuming it isn't normal operation?

(aside: I'm trying `rbspy` because`ruby-prof` was crashing with `Illegal instruction: 4`; trying to smoke out [my recently-inherited lmdb bindings](/doriantaylor/lmdb))
