### ISSUE TITLE
Document that rbspy is not (yet) an on-CPU profiler

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [rbspy/rbspy#265]
I was a bit unsure which stacks rbspy profiles. For the longest time I actually assumed it was collecting only on-CPU stacks.

As far as I understand though (based on https://github.com/rbspy/rbspy/pull/127), it currently collects stacks for all threads in a process. Is this what is usually called "wall" profiling?

It'd be great to have this explained in the rbspy docs!

**Comment by jvns** [comment]
great idea -- I can't find it anywhere in the docs either :).

do you know where you would have expected to find it? the repo for https://rbspy.github.io is https://github.com/rbspy/rbspy-docs

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This may be too prominent, but I'd consider this to possibly even be README worthy. As a user, when evaluating a profiler, I want to know:

* What is the overhead? -- The current README covers this quite well.
* Which operation or resource is this profiling? e.g., will it tell me where my CPU cycles went? -- This could be clearer.

One place I would definitely like to see some discussion of this is the rbspy vs stackprof page -- specifically because stackprof _does_ have an on-CPU profiling mode.

**Comment by jvns** [comment]
just added a note about this to the README! https://github.com/rbspy/rbspy/commit/163a1760ed69be8628585259acb989b70bb8fafa

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Wonderful, thank you!
