### ISSUE TITLE
Improve rbspy error reporting

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#268]
Right now, when people report bugs with rbspy, I'm unable to debug them because there's no way for people to submit a good crash report that would help me, and often it's not possible for me to reproduce the issue locally.

Some possibilities:

* maybe ask people to record the crash with`rr` so I at least have a record of the system calls they ran?
* improve error messages to include more information, like maybe a dump of the relevant memory

issues affected by this: #263, #243, #259, #266, #226

**Comment by jvns** [comment]
#289 made me think about this again. Maybe we could add an option which makes rbspy take a full core dump of the Ruby program it was profiling when it crashes? I think this could be as simple as just shelling out to `gcore`.

cc @acj @igorwwwwwwwwwwwwwwwwwwww  in case either of you have ideas of how to make the error reproduction process faster.

**Comment by acj** [comment]
I like that idea. IMO, the most useful bits of diagnostic info would be a core dump and the key memory addresses (in case they're wrong, or someone is using a custom ruby build) -- current thread, global symbol table, etc. Maybe we could pretty-print something like `StackTraceGetter`?

We may want to include a basic privacy warning if we capture a core dump. Someone can choose to send us that info to help with troubleshooting, but they should be aware that it's raw memory.

**Comment by acj** [comment]
With process pausing enabled by default and improved error messages, I'm hoping that this will become less of a problem. People who run into memory-related issues should get error messages with more diagnostic info. That will probably mean less +1-ing of e.g. the existing "No stack counts found" issues and more specific bug reports instead.

Marking this as closed for the purposes of the 0.6 release, but we may need to reopen it as feedback comes in.

**Comment by acj** [comment]
> So much better indeed

Glad to hear that! Thanks for the feedback.

> depends a lot on the OS and their security features

I think that's the issue, yeah. In an Ubuntu 20.10 VM (no customizations - only installed rust), I'm able to profile the command you mentioned. Hardening features like SELinux or AppArmor might make a difference depending on how they're configured. If you have time (and interest) to experiment with this, it would be great to understand what's causing the error.

**Comment by jarthod** [comment]
Ok thanks!

Yes I do have some time to experiment with this but I'm not sure where to start. I'm running Ubuntu 20.10 too so pretty standard but in my case it has been upgraded many times so it's not a "clean install". Here is my OS:
```
> sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
> uname -a
Linux desktop 5.8.0-49-generic #55-Ubuntu SMP Wed Mar 24 14:45:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
I tried checking if I have SELinux but it's not installed, I do have AppArmor though:
```
> sudo aa-status 
apparmor module is loaded.
81 profiles are loaded.
76 profiles are in enforce mode.
   /snap/core/10958/usr/lib/snapd/snap-confine
   /snap/core/10958/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /snap/core/4917/usr/lib/snapd/snap-confine
   /snap/core/4917/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/bin/evince
   /usr/bin/evince-previewer
   /usr/bin/evince-previewer//sanitized_helper
   /usr/bin/evince-thumbnailer
   /usr/bin/evince//sanitized_helper
   /usr/bin/freshclam
   /usr/bin/man
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/cups/backend/cups-pdf
   /usr/lib/lightdm/lightdm-guest-session
   /usr/lib/lightdm/lightdm-guest-session//chromium
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/lib/telepathy/mission-control-5
   /usr/lib/telepathy/telepathy-*
   /usr/lib/telepathy/telepathy-*//pxgsettings
   /usr/lib/telepathy/telepathy-*//sanitized_helper
   /usr/lib/telepathy/telepathy-ofono
   /usr/sbin/clamd
   /usr/sbin/cups-browsed
   /usr/sbin/cupsd
   /usr/sbin/cupsd//third_party
   /usr/sbin/mysqld
   /usr/sbin/named
   /usr/sbin/ntpd
   /usr/sbin/unbound
   /usr/share/hplip/plugin.py
   /usr/share/hplip/sendfax.py
   /usr/share/hplip/setup.py
   /usr/share/hplip/systray.py
   /usr/share/hplip/toolbox.py
   /{,usr/}sbin/dhclient
   libreoffice-senddoc
   libreoffice-soffice//gpg
   libreoffice-xpdfimport
   lsb_release
   man_filter
   man_groff
   nvidia_modprobe
   nvidia_modprobe//kmod
   snap-update-ns.chromium
   snap-update-ns.core
   snap-update-ns.glances
   snap-update-ns.gnome-system-monitor
   snap-update-ns.htop
   snap-update-ns.ike-qt
   snap-update-ns.kontena-lens
   snap-update-ns.ngrok
   snap-update-ns.pdftk
   snap-update-ns.slack
   snap-update-ns.snap-store
   snap.chromium.chromedriver
   snap.chromium.chromium
   snap.chromium.hook.configure
   snap.core.hook.configure
   snap.glances.glances
   snap.gnome-system-monitor.gnome-system-monitor
   snap.gnome-system-monitor.hook.configure
   snap.htop.htop
   snap.ike-qt.ikec
   snap.ike-qt.iked
   snap.ike-qt.qikea
   snap.ike-qt.qikec
   snap.ngrok.ngrok
   snap.pdftk.pdftk
   snap.snap-store.hook.configure
   snap.snap-store.snap-store
   snap.snap-store.ubuntu-software
   snap.snap-store.ubuntu-software-local-file
   tcpdump
5 profiles are in complain mode.
   /usr/sbin/sssd
   libreoffice-oopslash
   libreoffice-soffice
   snap.kontena-lens.kontena-lens
   snap.slack.slack
0 profiles are in kill mode.
0 profiles are in unconfined mode.
16 processes have profiles defined.
9 processes are in enforce mode.
   /usr/bin/freshclam (1565367) 
   /usr/lib/telepathy/mission-control-5 (7705) 
   /usr/sbin/clamd (1566722) 
   /usr/sbin/cups-browsed (2065641) 
   /usr/sbin/cupsd (2065633) 
   /usr/sbin/mysqld (1473) 
   /usr/sbin/ntpd (385528) 
   /usr/sbin/unbound (1412) 
   /snap/snap-store/518/usr/bin/snap-store (5570) snap.snap-store.ubuntu-software
7 processes are in complain mode.
   /snap/slack/39/usr/lib/slack/slack (1671583) snap.slack.slack
   /snap/slack/39/usr/lib/slack/slack (1671586) snap.slack.slack
   /snap/slack/39/usr/lib/slack/slack (1671587) snap.slack.slack
   /snap/slack/39/usr/lib/slack/slack (1671616) snap.slack.slack
   /snap/slack/39/usr/lib/slack/slack (1671638) snap.slack.slack
   /snap/slack/39/usr/lib/slack/slack (1671645) snap.slack.slack
   /snap/slack/39/usr/lib/slack/slack (1774715) snap.slack.slack
0 processes are unconfined but have a profile defined.
0 processes are in mixed mode.
0 processes are in kill mode.
```
Let me know if you want to move this discussion somewhere else and if you have ideas of things I should try ^^
