### ISSUE TITLE
Allow to set the `min_width` option from CLI to increase/reduce FlameGraph precision/fidelity

### ISSUE THREAD

**Issue by jarthod** [rbspy/rbspy#275]
I noticed that no matter how long I let `rbspy` run (e.g. 2-4 hours), many flames with more than 1000 samples were still missing from the SVG flamegraph. I found the `min_width` [option from inferno](https://docs.rs/inferno/0.10.1/inferno/flamegraph/struct.Options.html#structfield.min_width) as mentioned in #240 (by @liaden) which is currently set to the default of `0.1%`. I think this is a good default value to keep a decently sized output.

It could be useful for people like me who run long profiling (and so have many sample so good precision) to be able to decrease this number to have more details in smaller flames (I would probably want to go down to 0.01% if it doesn't crash my browser when opening the SVG ☺)

Has adding this option been discussed already? (sorry if I couldn't find the issue) would it be ok to add it? If so I can try sending a PR but I don't promise anything as I only tried rust a long time ago ;)

**Comment by jvns** [comment]
I don't think it's been discussed before, but this sounds reasonable -- I'd be happy to merge a PR that does this.

**Comment by jarthod** [comment]
Opened PR #276 :tada:
