### ISSUE TITLE
The version of rbspy on crates.io is quite old.

### ISSUE THREAD

**Issue by nelsonjchen** [rbspy/rbspy#277]
Maybe it could use a bump? Other than making it easy to install from crates.io:

* Not having users wondering why their rbspy doesn't work. The copy of a Rust software on crates.io is usually recentish, right? Apparently wrong. 
* Can show crates this tool depends upon that this tool depends upon them.
* Could get included in crater runs or stuff that looks across the whole Rust ecosystem. Though, I guess the tool wouldn't be popular enough to show up but you never know.

**Comment by jvns** [comment]
Oops, I didn't mean to close this since it's still not done. 

I tried to run `cargo build` and `cargo publish` from my laptop but I get a bunch of errors from `cargo publish` even though `cargo build` succeeds. Not sure why yet.

**Comment by jvns** [comment]
The new version of the crate is now published, thanks so much for reporting this! I'll track automating this in a separate issue.

**Comment by nelsonjchen** [comment]
Thanks for looking into this! By the way, I saw your blog post about [GitHub Actions and so on](debugging CI is frustrating
). [YSK, I have a demo setup for debugging windows builds on GitHub actions](https://github.com/nelsonjchen/reverse-rdp-windows-github-actions).
