### ISSUE TITLE
macOS M1 support

### ISSUE THREAD

**Issue by petethepig** [rbspy/rbspy#279]
Hi everyone!

I tried running rbspy on an M1 mac and it did not work, so I did some debugging. I have not fixed the issue yet, but I thought this could be helpful to anyone who might be looking at this in the future.

When you try to use rbspy on an M1 mac it fails with this error: `Ruby version not supported yet: . Please create a GitHub issue and we'll fix it!`. So it's pretty apparent that the version is not being read correctly.

So I looked at how the version was being detected and I was able to trace it down all the way from `rbspy` to `proc-maps` to [libproc-rs](https://github.com/andrewdavidmackenzie/libproc-rs).

### Summary

It looks like `libproc::libproc::proc_pid::regionfilename` and `proc_regionfilename` are returning incorrect names, here's the relevant code: https://github.com/andrewdavidmackenzie/libproc-rs/blob/d8d1c40dbd9d8cf9bc70314690c4a38180cdcc23/src/libproc/proc_pid.rs#L336

And as a result the memory region for libruby is not being detected correctly.

I added some code [here](https://github.com/rbspy/proc-maps/blob/master/src/mac_maps/mod.rs#L137) in `proc-maps` to print filenames and addresses and then compared it to `vmmap` output.

![Pasted_Image_2_4_21__10_13_PM](https://user-images.githubusercontent.com/662636/106996801-814af400-6736-11eb-8cb9-260c4e075e2d.png)

[here's a gist with this data in text form](https://gist.github.com/petethepig/e6b7c39f6a84def0d963615ae0fb0fb9)

### Next Steps

* [ ] find a way around this? maybe there's some other method we could use to filter these out / detect `regionfilename` correctly. 
* [ ] file a bug with Apple? It looks like `proc_regionfilename` is just returning incorrect information. I would love any help / pointers on this as I have never dealt with this before.

### Other Relevant Information

* This is only relevant for ruby running with **Rosetta**, I did not try the native version yet.
* I'm not sure if this is the only hurdle on the way to M1 support.

**Comment by benfred** [comment]
This might be a bit of a long shot - but does py-spy work on a M1 mac?  

Both py-spy and rbspy use the proc-maps crate - but py-spy also hits the 'get_dlyd_info'  https://github.com/rbspy/proc-maps/blob/master/src/mac_maps/mod.rs#L165-L168  . I'm wondering if we just haven't hit the need for this function with rbspy before.

If you're up for it - does running this get_dlyd_info function return the output you'd expect?

**Comment by petethepig** [comment]
`py-spy` does work. I will try `get_dlyd_info` tomorrow, this seems promising!

**Comment by petethepig** [comment]
@benfred It did work, was pretty easy to add actually https://github.com/rbspy/rbspy/pull/280
