### ISSUE TITLE
Mac CI build is flaky

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#287]
The MacOS CI build has a race and fails a lot. I'm not sure why the flaky test doesn't have the same flakiness issue on Linux.

**Comment by acj** [comment]
I think this is fixed now (#290, #296). Closing until we see it again.

**Comment by acj** [comment]
Reopening for linking/tagging purposes because I think I've finally found the root cause. The Mac build has been flaky again lately, and I had disabled the subprocess test on Windows because it was so unreliable. I think they've both been pointing at a logic bug in the recording code.
