### ISSUE TITLE
call rbspy in ruby thread reaturn: Error. Causes: environment variable not found

### ISSUE THREAD

**Issue by kewudu** [rbspy/rbspy#292]
I start rbspy record in ruby thread, but it print the following error:
```
 Error. Causes: 
environment variable not found
```

how can I know which environment variable missing?

rbspy record in shell terminal works fine in the same machine

**Comment by kewudu** [comment]
I find the problem, it seems that rbspy need HOME environment to save result,
so add HOME=/root environment variable the problem solved.

but why the error message not print which environment missing?

**Comment by acj** [comment]
I'm glad that you were able to solve the problem. It's a good point, though -- there are a few code paths where rbspy doesn't return an error, or returns an error but doesn't include enough info to understand the problem. I think we can fix this, so let's leave this issue open.

**Comment by acj** [comment]
Repro:

```
$ cat env-var-bug.rb
#!/usr/bin/env ruby

`unset HOME; sudo --preserve-env ./target/debug/rbspy record -s --silent -- ruby ci/ruby-programs/infinite.rb`
```

```
$ ./env-var-bug.rb
Error. Causes:
- HOME
- environment variable not found
HOME

Caused by:
    environment variable not found
```

The new message is a bit scruffy (separate problem), but it should make this issue easier to troubleshoot and fix.
