### ISSUE TITLE
speedscope output of frames with C functions not as useful as it perhaps could be

### ISSUE THREAD

**Issue by dalehamel** [rbspy/rbspy#302]
By default, C functions show up as the `file` attribute of the frame in speedscope output, per:

https://github.com/rbspy/rbspy/blob/master/src/ui/speedscope.rs#L135-L144

Here is a very simple snippet from the sample json output:

```
...
  "shared": {
    "frames": [
      {
        "name": "<c function>",
        "file": "sleep",
        "line": 0,
        "col": null
      }
    ]
  },
...
```

For a very basic C program running `sleep` we will just see the output in speedscope as `<c function>`:

![Selection_195](https://user-images.githubusercontent.com/618615/113341773-92aa1a00-92fb-11eb-952f-80d3c7d3b75a.png)

In some views, you can click on it to see the file attribute:

![Selection_196](https://user-images.githubusercontent.com/618615/113341959-dd2b9680-92fb-11eb-9f92-6458ce8f55da.png)

But in other views, this information is completely lost:

![Selection_197](https://user-images.githubusercontent.com/618615/113342138-1a902400-92fc-11eb-846a-5153e3657e2d.png)

However, I think the output is more useful if the C function name is given along side the `<c function>` label. To mock this up, I wrote a short go program to mutate the output (see end of issue). All that it does is append the "file" attribute to the "name" attribute of the frame, if the "name" is just `<c function>`. The same output snippet at before becomes (note that it is stripping default values, which speedscope seems not to mind):

```
...
  "shared": {
    "frames": [
      {
        "file": "sleep",
        "name": "<c function> : sleep"
      }
    ]
  }
...
```

![Selection_198](https://user-images.githubusercontent.com/618615/113342288-4f9c7680-92fc-11eb-942d-d2cf8bf4a9b6.png)
![Selection_199](https://user-images.githubusercontent.com/618615/113342286-4f9c7680-92fc-11eb-91bf-acfbcf4d55f8.png)

I believe we could achieve the same thing, by doing this same check inline in https://github.com/rbspy/rbspy/blob/master/src/ui/speedscope.rs#L136. Since this only affects the speedscope output, I think it is reasonable to fix this problem in rbspy's speedscope data renderer but wanted to open this issue to get the ball rolling on that discussion. @acj as you wrote the C symbol functionality, i'd love to get your opinion on this. I don't have experience with Rust, but could probably figure it out, though you'd likely be faster than me.

Note that I have not yet run this for more complicated ruby programs, but I believe it should remain as valid as it is with this simple program that is only sleeping.

Also note that for testing, the hosted https://www.speedscope.app/ can be used to verify how output is displayed, to avoid the hassle of setting up speedscope.

The full golang program:

```go
package main

import (
        "encoding/json"
        "fmt"
        "io/ioutil"
        "os"
)

// These structs generated by https://github.com/a-h/generate from
// the official schema at https://www.speedscope.app/file-format-schema.json
// only the required structs are used here

// FileFormatFile
type FileFormatFile struct {
        ActiveProfileIndex float64       `json:"activeProfileIndex,omitempty"`
        Exporter           string        `json:"exporter,omitempty"`
        Name               string        `json:"name,omitempty"`
        Profiles           []interface{} `json:"profiles"`
        Schema             string        `json:"$schema"`
        Shared             *Shared       `json:"shared"`
}

// FileFormatFrame
type FileFormatFrame struct {
        Col  float64 `json:"col,omitempty"`
        File string  `json:"file,omitempty"`
        Line float64 `json:"line,omitempty"`
        Name string  `json:"name"`
}

// Shared
type Shared struct {
        Frames []*FileFormatFrame `json:"frames"`
}

func printUsage() {
        fmt.Printf("Usage: %s FILE\n", os.Args[0])
        os.Exit(1)
}

func fixSpeedscopeOutput(json_file string) (string, error) {
        if _, err := os.Stat(json_file); err != nil {
                return "", err
        }

        json_bytes, err := ioutil.ReadFile(json_file)
        if err != nil {
                return "", err
        }

        var speedscope_data FileFormatFile
        err = json.Unmarshal(json_bytes, &speedscope_data)

        if err != nil {
                return "", err
        }

        for _, frame := range speedscope_data.Shared.Frames {
                if frame.Name == "<c function>" && frame.File != "" {
                        frame.Name = fmt.Sprintf("%s : %s", frame.Name, frame.File)
                }
        }

        fixed_json, err := json.Marshal(speedscope_data)

        if err != nil {
                return "", err
        }

        return string(fixed_json), nil
}

func main() {
        if len(os.Args) != 2 {
                printUsage()
        }

        json_file := os.Args[1]
        fixed, err := fixSpeedscopeOutput(json_file)

        if err != nil {
                fmt.Printf("Error: %v\n", err)
                os.Exit(1)
        } else {
                fmt.Printf(fixed)
        }
}

```

**Comment by acj** [comment]
Hey, thanks for the nice writeup. The way rbspy builds C stack frames is a bit silly currently. It uses the `relative_path` field to store the function name, but that field really should be empty (or "unknown") because we don't know which source file the C func is from.

If we fix this at the source when the `StackFrame` is constructed, I think we can do a few things at once:

- Improve speedscope presentation
- Stop misusing `relative_path`
- Make terminal output less confusing when using the default format. The output field ordering for C functions is confusing, and the angle brackets are used in a couple of different ways depending on context

For example, with this patch...

```diff
--- src/core/ruby_version.rs
+++ src/core/ruby_version.rs
@@ -296,8 +296,8 @@ macro_rules! get_stack_trace(
                         match get_cfunc_name(cfp, global_symbols_addr, source, pid) {
                             Ok(name) => {
                                 frame = StackFrame{
-                                    name: "<c function>".to_string(),
-                                    relative_path: name,
+                                    name: format!("{} [c function]", name),
+                                    relative_path: "(unknown)".to_string(),
                                     absolute_path: None,
                                     lineno: 0
                                 };
--- src/core/types.rs
+++ src/core/types.rs
@@ -60,8 +60,8 @@ impl StackFrame {
     // would be a constant but it has strings in it so it can't be.
     pub fn unknown_c_function() -> StackFrame {
         StackFrame {
-            name: "<c function>".to_string(),
-            relative_path: "unknown".to_string(),
+            name: "(unknown) [c function]".to_string(),
+            relative_path: "(unknown)".to_string(),
             absolute_path: None,
             lineno: 0
         }

```

... we get terminal output like

```
Time since start: 7s. Press Ctrl+C to stop.
Summary of profiling data so far:
% self  % total  name
100.00   100.00  sleep [c function] - (unknown)
  0.00   100.00  loop [c function] - (unknown)
  0.00   100.00  ccc - ci/ruby-programs/infinite.rb
  0.00   100.00  block in <main> - ci/ruby-programs/infinite.rb
  0.00   100.00  bbb - ci/ruby-programs/infinite.rb
  0.00   100.00  aaa - ci/ruby-programs/infinite.rb
  0.00   100.00  <main> - ci/ruby-programs/infinite.rb
```

... and speedscope looks like

![image](https://user-images.githubusercontent.com/27923/113483580-29004c00-9472-11eb-9894-06f8710fed7a.png)

... which is a more correct representation and is a bit easier to read, at least to my eye. WDYT?

**Comment by acj** [comment]
@dalehamel I feel pretty good about the change I mentioned above, so I'm going to move ahead with it. Please give it a try and let me know if it makes speedscope more useful for you. The changes are on master and will go out in the next release (likely tomorrow).

**Comment by dalehamel** [comment]
@acj amazing! I just gave it a shot and this looks much better. I was curious if it would be more practical to fix how the fields were used, and clearly it looks like it was. Thank you very much for quickly attending to this, it is a huge help.

**Comment by acj** [comment]
Glad to hear that. I'll close this, but feel free to reopen if you notice any other speedscope quirks that we can iron out.
