### ISSUE TITLE
Build failure on Apple Silicon

### ISSUE THREAD

**Issue by carlocab** [rbspy/rbspy#303]
We've been unable to build rbspy for Apple Silicon at Homebrew, despite its being supported since [v0.3.12](https://github.com/rbspy/rbspy/releases/tag/v0.3.12).

The build results in the following error:
```
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to run custom build command for `backtrace-sys v0.1.28`

Caused by:
  process didn't exit successfully: `/private/tmp/rbspy-20210403-43467-12kw83u/rbspy-0.4.1/target/release/build/backtrace-sys-6ba5e2b21149aac5/build-script-build` (exit code: 1)
```

Complete build logs available [here](https://github.com/Homebrew/homebrew-core/pull/74497/checks?check_run_id=2261639314), and the error starts [here](https://github.com/Homebrew/homebrew-core/pull/74497/checks?check_run_id=2261639314#step:7:246).

I suspect the failure is due to a misspecified `Cargo.lock` file. The build log suggests that `cargo` is trying to use `backtrace-sys v0.1.28`, which is a rather old version of `backtrace-sys`, dating back to about [2 years ago](https://crates.io/crates/backtrace-sys/0.1.28).

We pass the [`--locked`](https://rubydoc.brew.sh/Formula.html#std_cargo_args-instance_method) flag to `cargo` when building because we want our builds to be reproducible. Without this flag, `cargo` just pulls in the latest versions from crates.io.

I can see that you've recently updated your `Cargo.lock` file, but it still seems to use an old version of `backtrace-sys`.

Related: https://github.com/Homebrew/homebrew-core/pull/74497

**Comment by acj** [comment]
Thanks for the heads up. I've been meaning to upgrade the dependencies anyway, so I'll do that and then cut another release.

**Comment by acj** [comment]
Fixed in 0.4.2

**Comment by carlocab** [comment]
That helped a bit, but not enough, unfortunately:
```
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to run custom build command for `miniz-sys v0.1.12`

Caused by:
  process didn't exit successfully: `/private/tmp/rbspy-20210403-33743-1knknll/rbspy-0.4.2/target/release/build/miniz-sys-5464d4d6c6e23af4/build-script-build` (exit code: 1)
```

Logs: https://github.com/Homebrew/homebrew-core/pull/74501/checks?check_run_id=2262057559#step:7:223

**Comment by acj** [comment]
Ah, bummer. We might be able to upgrade flate2 to remove that dependency on miniz-sys. I'll look into it.

**Comment by carlocab** [comment]
Thanks. Wish I could help more, but I don't actually have an M1 machine to test anything on.

**Comment by acj** [comment]
Same 😕 

So, I've removed the dependency on miniz-sys. The latest changes are in master. Is there a way for you (or me) to try running the homebrew formula build on one of the `11-arm` CI workers before I make another release?

**Comment by carlocab** [comment]
We took a runner off the actions queue because it was acting up, so I was able to log into that and test it: it works! 🎉

**Comment by acj** [comment]
Excellent! Thanks for doing that. I'll make another release soon, probably tomorrow or so.

**Comment by acj** [comment]
v0.4.3 is released :)

**Comment by carlocab** [comment]
Thanks! Opened https://github.com/Homebrew/homebrew-core/pull/74649 to update this at Homebrew.

🤞 for ARM CI.

**Comment by carlocab** [comment]
Should be good now, though I had to tweak the test block a bit. Thanks for your work on this!

**Comment by acj** [comment]
Thanks for yours!

I looked at the test changes and wanted to give you a heads up that this format is outdated:

> 100.00   100.00  <c function> - unknown

It will look more like this now:

> 100.00   100.00  (unknown) [c function] - (unknown)

Maybe a test fixture in the formula needs to be regenerated?

**Comment by carlocab** [comment]
>Maybe a test fixture in the formula needs to be regenerated?

That's possible. I'm not actually familiar with what's going on here (and haven't really had the pleasure of using `rbspy` much), so I didn't know any better 😅 

If you've got any tips for fixing up the test block (or if you could spare the time to open a PR), that'd be much appreciated.
