### ISSUE TITLE
feat: release docker images

### ISSUE THREAD

**Issue by dalehamel** [rbspy/rbspy#304]
Although rbspy is already a static / mostly static binary, it could be helpful from a distribution standpoint to publish a docker image when in CI, to either dockerhub or quay.io, and when a release is done, tag this docker image with the release.

This would mostly be useful for other docker build pipelines that incorporate rbspy, as they will be able to use docker's `COPY --from` support, to pull the rbspy binary out of the docker image. Presently, we download rbspy from github releases inline in our docker builds, but if we were able to pull it out of a docker image we could simplify our build process a little bit.

I think this makes the most sense for the linux x86_64 targets, perhaps a single docker image per architecture? Or, one image per release build, tagged by architecture / libc?

**Comment by acj** [comment]
@dalehamel It's a WIP, but there are some images available for testing: https://hub.docker.com/r/rbspy/rbspy

There are two images, one for musl (static) and one for "gnu" / glibc. Both have support for x86_64 and aarch64. If you have a chance, please try them out and let me know how it goes.

**Comment by dalehamel** [comment]
very cool @acj thanks again for another great addition. We'll give these a try shortly!
