### ISSUE TITLE
Multiple versions of single method

### ISSUE THREAD

**Issue by chrisseaton** [rbspy/rbspy#317]
Leading on from #315, which had extra impossible stack frames and was fixed thank you, I've still got some misleading frames.

```ruby
def foo
  10.times do
    bar
  end
end

def bar
  GC.stat
  6000.times do
    baz(rand(10), rand(10), rand(10))
  end
end

def baz(a, b, c)
  [a, b, c].sort[1]
end

loop do
  foo
end
```

```
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
```

<img width="1907" alt="Screenshot 2021-04-20 at 14 15 30" src="https://user-images.githubusercontent.com/341094/115402324-3abc5000-a1e3-11eb-8781-b092c5463075.png">

This trace shows `baz` as three separate methods - `baz`, `baz [c function]` and `(unknown) [c function]`. I know they're all really just normal `baz` because they're all in turn calling `sort`.

**Comment by chrisseaton** [comment]
[rbspy-2021-04-20-NJSZdqvjkM.flamegraph.svg.zip](https://github.com/rbspy/rbspy/files/6343967/rbspy-2021-04-20-NJSZdqvjkM.flamegraph.svg.zip)

**Comment by acj** [comment]
Thanks for your patience. Were you running rbspy 0.5.0 when you saw this behavior? Running a build from master on macOS with the same ruby version you mentioned, I get this:

![image](https://user-images.githubusercontent.com/27923/117555906-473d0700-b031-11eb-883d-59fd3d5245db.png)

... which seems correct. I do get `(unknown) [c function]` frames if I run with `--nonblocking`, though. So the fix from #315 also applies here if you're able to run rbspy in the default mode (i.e., with process pausing).

Even for the nonblocking mode, I think we could reduce the impact of this bug. I don't fully understand the reason for the "unknown" C frames that we get sometimes, but I think we could work around it. What I'd propose is that we drop C frames whose name can't be resolved. My guess is that they're a different type of structure, or maybe there's a race condition when we're taking the snapshot. Whatever the cause, they're not very helpful to have in the profiling output.

Possible fix:

```diff
--- src/core/ruby_version.rs
+++ src/core/ruby_version.rs
@@ -293,23 +293,22 @@ macro_rules! get_stack_trace(
             let cfps = get_cfps(thread.cfp as usize, stack_base(&thread) as usize, source)?;
             for cfp in cfps.iter() {
                 if cfp.iseq as usize == 0 {
-                    let mut frame = StackFrame::unknown_c_function();
                     if let Some(global_symbols_addr) = ruby_global_symbols_address_location {
                         match get_cfunc_name(cfp, global_symbols_addr, source, pid) {
                             Ok(name) => {
-                                frame = StackFrame{
+                                let frame = StackFrame{
                                     name: format!("{} [c function]", name),
                                     relative_path: "(unknown)".to_string(),
                                     absolute_path: None,
                                     lineno: 0
                                 };
+                                trace.push(frame);
                             },
                             Err(e) => {
                                 debug!("Unknown C function: {:?}", e);
                             }
                         }
                     }
-                    trace.push(frame);
                     continue;
                 }
                 if cfp.pc as usize == 0 {

```

**Comment by acj** [comment]
@chrisseaton Do you still see this behavior after upgrading to rbspy 0.6.0?

**Comment by chrisseaton** [comment]
Does seem better now for my example, thanks!
