### ISSUE TITLE
Support `--` to indicate the start of the profiled command

### ISSUE THREAD

**Issue by casperisfine** [rbspy/rbspy#318]
If the command you want to profile contain `-` or `--` arguments it confuse `rbspy`:

```
$ rbspy record --silent ruby -e 'sleep 10'
error: Found argument '-e' which wasn't expected, or isn't valid in this context

USAGE:
    rbspy record --pid <PID> --raw-file <FILE> --silent
```

A common unix convention is to use `--` to mark the end of the option flags, so the above would be:

```
$ rbspy record --silent -- ruby -e 'sleep 10'
```

But from what I can tell it doesn't work:

```
$ /tmp/rbspy record -- ruby -e 'sleep 10'
Press Ctrl+C to stop
Wrote raw data to /app/.cache/rbspy/records/rbspy-2021-04-23-wJVi139p8C.raw.gz
Writing formatted output to /app/.cache/rbspy/records/rbspy-2021-04-23-WsXMok6ywH.flamegraph.svg
[2021-04-23T08:24:23Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/ui/flamegraph.rs:47:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Unfortunately I have no prior rust experience, so not sure where to begin to fix this.

**Comment by acj** [comment]
The `--` convention is supported. This works for me:

```
$ rbspy record --silent -- ruby -e 'sleep 10'
Press Ctrl+C to stop
Wrote raw data to /home/vagrant/.cache/rbspy/records/rbspy-2021-04-23-QQnbYK3niU.raw.gz
Writing formatted output to /home/vagrant/.cache/rbspy/records/rbspy-2021-04-23-SoCsEstBOS.flamegraph.svg
```

Can you tell us more about your environment? OS, Ruby version, whether you're running rbspy in a container, etc.

If you're able to build rbspy from source, there are several unreleased fixes that should improve the error messaging for cases like this.

**Comment by casperisfine** [comment]
Uh, weird, it works now. I think it's the ruby that I was using that had problem. Sorry for the bogus report.
