### ISSUE TITLE
[Question/Doc] linux musl vs non musl version

### ISSUE THREAD

**Issue by ylecuyer** [rbspy/rbspy#322]
Hello,

In the release page there are multiple versions for the Linux binary but it is not explained what is the difference in the doc (https://rbspy.github.io/installing/)

For linux x86_64 it looks like there are two options (which is not the case for other systems):

1. rbspy-x86_64-musl.tar.gz
2. rbspy-x86_64-unknown-linux-gnu.tar.gz

Would it be possible to know what is the difference between the two?

**Comment by acj** [comment]
Hello. Yes, we should mention this distinction in the docs. The difference is that the -musl binaries are statically linked against the musl libc library and don't require a specific libc to be installed on your system. The -gnu binaries are dynamically linked against GNU libc and a couple of other libraries, so those need to be installed.
