### ISSUE TITLE
rbspy with yjit

### ISSUE THREAD

**Issue by dalehamel** [rbspy/rbspy#339]
It looks like [yjit](https://bugs.ruby-lang.org/issues/18229) may be merged [as early as ruby 3.1.0](https://bugs.ruby-lang.org/issues/18229#note-11)

I would imagine that this will pose problems for rbspy if ruby is run with `--yjit` to enable it, as the current methods for snapshotting the stack likely will not work with it.

@acj thought I'd raise this for you to take a look at, to assess how difficult it might be to support ruby processes using yjit, as if it offers real-world performance benefits, it will probably gain adoption quite rapidly.

**Comment by dalehamel** [comment]
@acj I know that some fine folks here at Shopify are working on it, and I remember talking to them a few months ago, wondering what compatibility with rbspy might be like, but so far it is still an open question I think.

I believe that stuff like stackprof should still work with yjit but I'm not sure about the approach rbspy takes. I tried to see if it would "just work" with a production process this morning, but it looks like the version we are using internally is against ruby 3.1.0 prerelease, so rbspy refuses to try without the headers added.

I would guess that one of the following will be the case:

- Things will "just work"
  - If the code paths we are using now are unaffected by yjit, stack sampling should just continue to work. I'm not terribly optimistic that this will be the case, but hey, it'd be nice.
- We need to add new cases to handle yjit
  - I think this is the most likely case, where we need to add some if/else handling to detect yjit, and some net-new code to be able to map from the compiled instructions back to the actual YARV that originated it, where we should then be able to (hopefully) just use the current code path in rbspy that is able to determine the source code lines, etc.
- Significant modifications required
  - This would be the worst case, in the event that getting a mapping from the JIT'd code back to YARV is difficult / impossible. In this case, we might need to actually have ruby/ruby implement something like [what NodeJS does](https://developers.redhat.com/blog/2017/09/11/profiling-nodejs-applications-with-linux-performance-tools), implementing a "perf map" that maps the JIT'd code back to the source (something analogous to the `--perf-basic-prof` flag)
  
  
Probably the best next-step would be to pull in the yjit patches onto a branch, import the headers on that branch, and just try it out and see what happens to see which of the above cases we fall into.

**Comment by maximecb** [comment]
We use the same stack of Ruby control frames that CRuby does, so if you're only looking at that stack, rather than the C stack, then it should "just work" ?

@tenderlove what do you think?

**Comment by acj** [comment]
Thanks, @maximecb. That's encouraging. I think we use only the Ruby control frames to walk through VM memory. I should have time over the next week to make a branch with 3.1 bindings and run a few tests.

**Comment by maximecb** [comment]
One small difference is we added a `jit_return` object to the control frames for when JIT code is returning to JIT code.

**Comment by tenderlove** [comment]
> @tenderlove what do you think?

Yes, I think this is an accurate assessment.

**Comment by acj** [comment]
It does seem to work with YJIT enabled, at least for my simple test cases. There are binaries with ruby 3.1.0-pre support attached to [this CI run](https://github.com/acj/rbspy/actions/runs/1301400573) if anyone would like to try it out.

**Comment by dalehamel** [comment]
@acj yup i just gave it a shot and it seems to be working on a real app, only question now would be to determine if that jit_return field poses a problem, i guess with a test case of a jit'd function calling another jit'd function than returning definitely shows both. Either way the early results are quite promising :+1:

**Comment by acj** [comment]
@dalehamel 

> i just gave it a shot and it seems to be working on a real app

Nice. Thanks for doing that.

> only question now would be to determine if that jit_return field poses a problem

We use a generated struct (via bindgen) for the control frames, so it should work. I see the new field in the 3.1.0-pre bindings [here](https://github.com/acj/rbspy/commit/e51299d8a24b0f6289cc6bfdc58155a256489b7f#diff-37ad0d8b3aefc1c4e8a0424f265a4db10bd543656fa129783d14605b5047a035R5561).
