### ISSUE TITLE
Expand the public API to support custom recorder development

### ISSUE THREAD

**Issue by saunderst** [rbspy/rbspy#346]
I've recently been working on a project which implements a new `Recorder` trait to create a custom recorder, similar to `Recorder::record()` but with additional functionality.  Because of limitations in the API, I had to use a fork of `rbspy` in order to control the sampler and outputter from within our project.

If the API could be extended to allow access to the `sampler` and `ui` modules, this would enable outside projects to include custom recorders based on the official `rbspy` crate.

**Comment by acj** [comment]
Thanks, @saunderst. I'll cut a release for this.

(Discussion began in #344.)
