### ISSUE TITLE
Forked version fails CI on 0.9.1

### ISSUE THREAD

**Issue by saunderst** [rbspy/rbspy#349]
FYI: When running CI on my fork, this line fails because `.cargo/git` doesn't exist:

https://github.com/rbspy/rbspy/blob/e78290f0c4da86722795a8533724e1ba99b3579e/ci/freebsd-build.sh#L25

Possibly the file was cached for `rbspy/rbspy` during some earlier stage of development?

**Comment by acj** [comment]
Thanks for flagging this. I saw it fail in another repo and should be able to use the same workaround here.
