### ISSUE TITLE
Unable to install on ubuntu 20.04

### ISSUE THREAD

**Issue by hurricup** [rbspy/rbspy#351]
Ubuntu 20.04
cargo installed from apt 1.53.0

When trying to build:
```
error: failed to parse manifest at `/home/user/rbspy-repo/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

Googling says it's because of some new rustc, but manifest requires 0.4, so why is it necessary to do anything?

**Comment by acj** [comment]
Thanks for pointing this out. We need to update the minimum rust version (probably ~1.56) now that we're on 2021 edition.

Are you able to install a newer rust toolchain, e.g. using rustup? If you're not making changes to the source, we also have pre-built binaries on the releases page -- both the musl and unknown-linux-gnu binaries should work on Ubuntu 20.04.

**Comment by hurricup** [comment]
Well, if it's unavoidable, i'll figure out installing I presume.

Still would be nice to avoid this and use packages shipped with ubuntu:
- 16.04 provides 1.47.0
- 18.04 provides 1.53.0
- 20.04 provides 1.53.0

I'm not really familiar with rust development and don't know if it's possible. If not, additional building instructions would be nice to have at https://rbspy.github.io/installing/

**Comment by acj** [comment]
Yes, I agree. Some of our dependencies need 1.56+, so unfortunately it's needed for rbspy too. We'll try to maintain compatibility with Ubuntu's packages in the next cycle. It looks like 22.04 will ship with 1.56.

**Comment by hurricup** [comment]
Seems `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y` works like a charm for unattended set up
