### ISSUE TITLE
Tests writing to HOME

### ISSUE THREAD

**Issue by viraptor** [rbspy/rbspy#354]
While trying to package rbspy for nix, I found that in environments where HOME is not writable, the `test_arg_parsing` calls `Args::from` calls `output_filename(home...)`, which does `DirBuilder::new().recursive(true).create(&dirname)?;`.

Ideas: A possible quick workaround would be for tests to provide HOME that points to some `mktemp` result. Less hacky thing could be to move the the creation to when it's actually needed.

Related to https://github.com/NixOS/nixpkgs/pull/161209

**Comment by acj** [comment]
Thanks! A quick fix for now, and eventually I want to do a larger cleanup of argument parsing.

**Comment by viraptor** [comment]
Confirming that this fixed the issue and how the nix package completes including the tests.
