### ISSUE TITLE
Broken link to installation instructions 

### ISSUE THREAD

**Issue by mslinn** [rbspy/rbspy#363]
The [docs](https://rbspy.github.io/) have a broken link under **Quick start**: 

> Otherwise, check out the [installing](https://rbspy.github.io/installing/index.html) section to get rbspy running on your computer.

The resulting page says:

> [Document not found (404)](https://rbspy.github.io/#document-not-found-404)
This URL is invalid, sorry. Please use the navigation bar or search to continue.

**Comment by acj** [comment]
Thanks! Fixed in https://github.com/rbspy/rbspy.github.io/commit/368d1b6b817d10beb2b9eaff7a2fd5796ad8b816.

**Comment by wodin** [comment]
The same problem exists in the release notes:

![image](https://github.com/rbspy/rbspy/assets/4579020/20a4c7fc-35ab-49f5-803e-aafdac48037f)

**Comment by acj** [comment]
Fixed there, too. Thanks for the heads up.
