### ISSUE TITLE
memory allocation of 1266630535279424 bytes failed

### ISSUE THREAD

**Issue by lilith** [rbspy/rbspy#369]
I keep getting these errors:

```
memory allocation of 1266630535279424 bytes failed
Dropped 1942/3883 stack traces because of errors. Please consider reporting a GitHub issue -- this isn't normal.
Wrote raw data to /home/lilith/.cache/rbspy/2022-09-02-xtE2IFFIo5.raw.gz
Wrote formatted output to compute.svg
Something went wrong while rbspy was sampling the process. Here's what we know:
- Failed to copy memory address 0

memory allocation of 1266631498167104 bytes failed
memory allocation of 1266632205292352 bytes failed
Dropped 928/1855 stack traces because of errors. Please consider reporting a GitHub issue -- this isn't normal.
Wrote raw data to /home/lilith/.cache/rbspy/2022-09-02-BcLchUXMqP.raw.gz
Wrote formatted output to cached.svg
Something went wrong while rbspy was sampling the process. Here's what we know:
- Failed to copy memory address 0
rbspy is recording traces. Press Ctrl+C to stop.
Executed rules, transfer detection, and overrides in   5.687500   0.125000   5.812500 (  7.259987)
memory allocation of 1266627042820928 bytes failed
```
[2022-09-02-BcLchUXMqP.raw.gz](https://github.com/rbspy/rbspy/files/9481337/2022-09-02-BcLchUXMqP.raw.gz)

**Comment by acj** [comment]
Thanks for the report. A few questions to get started:
- Which Ruby version are you using?
- and on which OS?
- Which recording options are you using?
- Are you able to share any code for repro purposes?

If you aren't recording with `--nonblocking`, that might be worth a try.

**Comment by acj** [comment]
One of the changes in 0.13.0 might have fixed this issue. Please give it a try if you can.

Let's also merge this conversation into #370.

**Comment by acj** [comment]
73126bb0e3debe325c6716bdcb0d3a01922a3de0 might resolve some of the malloc errors. It's not in today's release, but it will be in the next one.
