### ISSUE TITLE
(Note: may not be a bug) Build fails without `--locked` from crate and HEAD

### ISSUE THREAD

**Issue by steakknife** [rbspy/rbspy#377]
## Speculative cause

- clap API breakage

## Environment

- rust stable 1.67.1
- CentOS 8 Stream x86_64

## Work

- `cargo install rbspy --locked` 
- `cargo install rbspy --locked --git https://github.com/rbspy/rbspy`

## Fail

- `cargo install rbspy` 
- `cargo install rbspy --git https://github.com/rbspy/rbspy`

<details>
<summary>Output</summary>

```
   Compiling rbspy v0.16.0 ()
error: cannot find derive macro `ArgEnum` in this scope
   --> src/core/types.rs:142:10
    |
142 | #[derive(ArgEnum, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
    |          ^^^^^^^
    |
note: `ArgEnum` is imported here, but it is only a trait, without a derive macro
   --> src/core/types.rs:8:5
    |
8   | use clap::ArgEnum;
    |     ^^^^^^^^^^^^^

error[E0599]: no variant or associated item named `value_variants` found for enum `OutputFormat` in the current scope
   --> src/core/types.rs:181:15
    |
144 | pub enum OutputFormat {
    | --------------------- variant or associated item `value_variants` not found for this enum
...
181 |         Self::value_variants()
    |               ^^^^^^^^^^^^^^ variant or associated item not found in `OutputFormat`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `value_variants`, perhaps you need to implement it:
            candidate #1: `ArgEnum`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rbspy` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

</details>

Keep up the good work 🍻

**Comment by acj** [comment]
Thanks for the heads up. I'm going to update the documentation to include `--locked`, which should help anyone who's new to rbspy. Migrating to clap 4.x is on my to-do list as well.

There's a good discussion of this (IMO surprising) Cargo behavior in https://github.com/rust-lang/cargo/issues/7169.

**Comment by steakknife** [comment]
My general opinion about software dependencies management: 

If a project or package ships a lock file, respect it for sane & usable defaults.
