### ISSUE TITLE
Thanks for building this awesome tool!!

### ISSUE THREAD

**Issue by abhishekS03** [rbspy/rbspy#383]
@jvns We were struggling a lot with the performance of Ruby processes. Code-level profiling was not helping much as there was a lot of data and the issue was not getting reproduced in the test instances, but the issue was identified within minutes when we used this excellent process monitoring tool. So cool!! Thanks a lot!

**Comment by jvns** [comment]
thank you! @acj has been doing literally all of the work for the last ~3 years so all of the thanks are due to him at this point :)

**Comment by acj** [comment]
#62
