### ISSUE TITLE
Switch from elf to goblin

### ISSUE THREAD

**Issue by kamalmarhubi** [rbspy/rbspy#50]
The [elf] crate hasn't been updated in over a year. [Goblin] is much more actively developed. A few relevant pros over elf:
- zero-copy
- supports the executable fromats of macos (mach-o) and windows (pe32/64) which rbpsy will need down the line
- has labyrinth goblins on its readme page.

[elf]: https://github.com/cole14/rust-elf/
[goblin]: https://github.com/m4b/goblin

**Comment by thbar** [comment]
This is being happening in the [mac-support](https://github.com/rbspy/rbspy/tree/mac-support) branch.

**Comment by jvns** [comment]
Right now in the `mac-support` branch I'm working on using goblin for Mach-O support., but I'm leaving the Linux ELF code alone for today. Will work on moving everything to gobiin in a separate PR.

**Comment by jvns** [comment]
This isn't blocking anything but it would be nice to have if anyone is excited about to taking it on.

**Comment by acj** [comment]
Resolved by https://github.com/rbspy/rbspy/commit/2d3c33625dccfc58f9dcd349672f429db331b3bf.
