### ISSUE TITLE
Flamegraph gem support

### ISSUE THREAD

**Issue by SamSaffron** [rbspy/rbspy#51]
It would be cool to have a flamegraph gem support or perhaps a raw mode so you could generate the flamegraph using your favorite tool or even analyse with stackprof direct. (if a compatible raw mode could be established) 

Flamegraph gem is a bit more interactive than the static svg it makes it a bit easier to dig into things. 

https://github.com/SamSaffron/flamegraph

**Comment by jvns** [comment]
oh, interesting! There actually is a raw mode -- by default `rbspy record` both writes raw data to a text file (that's the same format flamegraph.pl expects) and generates a SVG flamegraph. Curious to know if you think this is enough -- should we be providing another format here?

here's an example of `rbspy record` output, where it prints the path to the raw file and the svg.

```
Recording data to /home/bork/.cache/rbspy/records/rbspy-2018-01-22-QHreWVuzwd.txt
Press Ctrl+C to stop
^CInterrupted.
Writing flamegraph to /home/bork/.cache/rbspy/records/rbspy-2018-01-22-QHreWVuzwd.svg
```

**Comment by SamSaffron** [comment]
Let me try this out tomorrow and let you know, thanks!
