### ISSUE TITLE
Easily access graphs from prd systems

### ISSUE THREAD

**Issue by SamSaffron** [rbspy/rbspy#52]
One huge pain point with `svg` and `html` based reports is that you need to figure out how to transport the graphics from a production server back to your local box. 

It would be super cool if rbspy was able to upload encrypted payloads to the cloud and then you could easily access them: 

```
% rebspy record PID --duration 1.5 --online
visit the following url to see the graph: 
https://rbspy-reports.com/graphs/12345#MAGIC_DECRYPTION_KEY
``` 

On our side I would be super happy to donate a digital ocean instance or 2 for the cause if you wish to build something like this.

**Comment by jvns** [comment]
I love the idea of a `--duration` flag, will likely add that this week.

This is a really interesting idea. I think it's a little early in the project for it right now (there are still some fundamental issues with recording stack traces that I'm prioritizing), but thanks for suggesting it!

**Comment by DanielHeath** [comment]
@SamSaffron I don't follow - if you can `ssh` into a host, you can also `scp` from it, right? 

For that matter `rbspy record` tends to generate pretty small data files; perhaps zip + base64 + copy/paste into a local `rbspy report` session would do?

**Comment by acj** [comment]
Closing since a good workaround has been suggested, and uploading reports is out of rbspy's scope for now. Thanks, all.
