### ISSUE TITLE
Add feature that tells `rbspy record` how long to record

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#53]
`--duration` or something. Often it's useful to record 60 seconds or so of profiling data, and it's annoying to have to manually start and stop the recording after 60 seconds.

@samsaffron indirectly suggested this in https://github.com/rbspy/rbspy/issues/52.

**Comment by liaden** [comment]
I'd be willing to take this on similar to the sampling rate PR.

**Comment by jvns** [comment]
@liaden that sounds great, go for it!

**Comment by jvns** [comment]
fixed in #58
