### ISSUE TITLE
Automatically suggest reporting an issue for high numbers of dropped frames

### ISSUE THREAD

**Issue by henrik** [rbspy/rbspy#54]
This is a lazy suggestion having only read the README, so maybe this already happens.

README says:

> A typical error message here is something like "Dropped 13/3700 stack traces because of errors". If you're seeing high error rates (more than 1/100 or so), please create an issue.

My "don't (just) document what you can automate" instincts make me wonder: Could it make sense for rbspy to detect high error rates and say something like "This error rate is quite high. Unless you expect it to be, please create an issue: https://github.com/rbspy/rbspy/issues/new"?

It probably makes sense to still mention it in the README since people who get lower error rates and see that message are probably helped by learning that a low rate is not abnormal. Hm, though depending on the current error message, maybe saying something to that effect could be helpful and save a trip to the README. "This amount of dropped stack traces is usually fine. Read more: …"

Keep up the great work!

**Comment by jvns** [comment]
finally got around to this, thanks :)
