### ISSUE TITLE
rbspy doesn't work if the Ruby process is using jemalloc

### ISSUE THREAD

**Issue by SamSaffron** [rbspy/rbspy#59]
```
sam@ubuntu discourse % irb 
irb(main):001:0> RUBY_VERSION
=> "2.4.2"
irb(main):002:0> `rbspy snapshot --pid #{Process.pid}`
Error. Causes: 
- Couldn't determine Ruby version
- Heap map not found for PID: 13599
```

```
 % uname -a
Linux ubuntu 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

Relevant env

```
% export | grep RUBY
RUBY_GLOBAL_METHOD_CACHE_SIZE=131072

% export | grep LD_PRE
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so

```

Also for some reason cargo build is taking forever, are there any tricks to getting it to build?

**Comment by liaden** [comment]
I just ran with 2.3.1 within irb and it worked for me. I wonder if jemalloc is causing it to place the heap maps in a different location?

**Comment by jvns** [comment]
huh interesting! Can you paste the output of `/proc/13599/maps`?

**Comment by jvns** [comment]
`cargo build` should normally take 5-10 minutes or so the first time you run it (compiling all the dependencies takes time), and subsequent runs should be faster (~15 seconds)
