### ISSUE TITLE
Add option to profile all subprocesses of a given PID

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#61]
It's a pretty common pattern in web services (eg Unicorn) to use a process supervisor that forks a bunch of Ruby subprocesses to run the web service. Could be useful to add a `--subprocesses` option that will profile all subprocesses of a given PID.

Another related issue is -- @liaden described an issue where they frequently kill their Ruby workers and start new ones (every 1-3 minutes or so). So tracking new workers under a process and profiling the new workers when they start could be useful.

This is basically like strace's `-f` option.

**Comment by Church-** [comment]
@jvns Just to make sure I'm tracking correctly. So for snapshots we'd want to have a flag to profile any and all sub-processes of the supplied PID? And for record would we want to either record all sub-processes that are already running and/or monitor for any freshly created ones while the profiler is running?
