### ISSUE TITLE
'allocator memory exhausted' error when spying on a Rails process

### ISSUE THREAD

**Issue by ragesoss** [rbspy/rbspy#64]
I'm giving this a spin by trying to profile bits of [my Rails app](https://github.com/WikiEducationFoundation/WikiEduDashboard).

Usually, when I load a page on the spied-upon rails server, rbspy exits immediately like this:

```
$ sudo rbspy record --pid 32471
Recording data to /root/.cache/rbspy/records/rbspy-2018-01-25-tw0bEjjEZq.txt
Press Ctrl+C to stop
fatal runtime error: allocator memory exhausted
Illegal instruction
```
It works for lighter page loads, like json endpoints that don't load or serve all that much data, but for typical tasks in my app that I'd like to profile, I haven't been able to get around this error.

**Comment by liaden** [comment]
Which endpoints are having an issue? Is it problematic in dev as well as prod?

**Comment by ragesoss** [comment]
@liaden I've only tried it in dev. It seems to be inconsistent, but more likely to crash on large sql queries and/or ones that send a lot of data.

Also, sometimes after it's crashed once, it will crash again immediately if I try to spy again on the same still-running rails server process (even if I don't load any pages).

I can try to provide more details, but I'm not sure which ones are likely to be useful.

**Comment by jvns** [comment]
this is an interesting issue, thanks for reporting! what Ruby version are you using? I made a PR with a mitigation in #65, which should help a little bit -- will make a new release from that so you can try it.

**Comment by ragesoss** [comment]
Ruby 2.5.0. :)

**Comment by jvns** [comment]
@ragesoss can you try with the latest release and see if it works any better? https://github.com/rbspy/rbspy/releases/tag/v0.1.3

If there are still a lot of errors, it would be great if you could run rbspy as  `env RUST_LOG=debug rbspy` and paste the output somewhere.

**Comment by ragesoss** [comment]
Yes, it works much better! If I spy the already-started rails server, it doesn't crash now.

With or without `env RUST_LOG=debug`, I don't see any errors or logging when I spy the process and do lots of page loading on the app.

The flamegraphs look like they might only be capturing the first page load or so. But it looks like logging worked; it captured 10 MB in the text file, compared to mostly less than 1MB before crashing before.

![activity5](https://user-images.githubusercontent.com/848483/35368268-6164dd1c-0137-11e8-8047-e3bafdfcb9de.png)

**Comment by liaden** [comment]
The default rate for sampling is every 10ms so if you have some pages that are really fast you may not capture more than one sample of it. If you take a look at at the `.txt` file, you could attempt to filter out the idle times where `httpserver.rb` is at the top of the stack. 

Alternatively, you could have a bash script that curls the pages to minimize idle time.

**Comment by jvns** [comment]
if you do `rbspy record --pid YOUR_PID` and then press ctrl+c after a while how many stack traces does it say it dropped? if the rate is high (like more than 1%) it would be good to know about it

**Comment by ragesoss** [comment]
@jvns 
`Dropped 28/3599 stack traces because of errors.`

**Comment by ragesoss** [comment]
More progress to report. I got my first useful result (graph below).

Caveat:  `Dropped 51/105 stack traces because of errors.` Maybe from lots of database queries that are happening in the middle of this code that rbspy can't trace?

I am trying to profile one part of my app that I know is pretty slow: rendering a certain complex json view. In order to isolate the code I wanted to profile, I put this the top:

```ruby
spawn("sudo rbspy record --pid #{Process.pid}")
```

And this at the bottom:

```ruby
spawn("sudo kill -INT #{Process.pid}")
```

That sort pattern — setting the start/stop points within the code I want to profile — is probably something I'll want to do a lot.

![weeks](https://user-images.githubusercontent.com/848483/35409984-b29bbd7c-01c8-11e8-921c-dde71a30ab30.png)

**Comment by jvns** [comment]
> I am trying to profile one part of my app that I know is pretty slow: rendering a certain complex json view. In order to isolate the code I wanted to profile...

If you want to profile a specific part of your code, it's almost certainly better to use [stackprof](https://github.com/tmm1/stackprof) than rbspy. the main difference between stackprof and rbspy is that stackprof is a gem you include in your process. and then say 

```
profile = StackProf.run(mode: :cpu, interval: 1000) do
  ...
end
```

to get a profile, and rbspy lets you profile Ruby processes from the "outside". different tools for different usecases!

**Comment by ragesoss** [comment]
> If you want to profile a specific part of your code, it's almost certainly better to use stackprof than rbspy. 

Good to know!

**Comment by jvns** [comment]
closing this since we fixed the original issue!
