### ISSUE TITLE
[mac-support] cargo test hangs 

### ISSUE THREAD

**Issue by thbar** [rbspy/rbspy#70]
Thanks for your great work on rbspy, first!

I tried out the `mac-support` branch tonight (#69). `cargo build` went fine, but `cargo test` seems to hang here:

![2018-01-26 at 22 31](https://user-images.githubusercontent.com/10141/35461573-ab3f2228-02e8-11e8-816a-fe3a84a4d8b4.png)

If I move the mouse over the terminal window, I'll see the Mac OS spinner (see [link](https://support.apple.com/kb/PH4502?locale=en_US)).

If I open Activity Monitor, something very unusual appears: the monitor shows no process at all, and no system statistics anymore.

There is no trivial way to close the window (I cannot open a new terminal etc), so I'll just reboot my machine :smile: 

Just wanted to report back with this (I will make further tests).

**Comment by thbar** [comment]
Forgot to add: I'm on High Sierra 10.13.3.

**Comment by thbar** [comment]
Trying to log into that machine via SSH from another machine just hangs too:

```
21:24 $ ssh thbar@machine.local
Last login: Fri Jan 26 22:24:07 2018
# no cursor there
```

and I cannot log out at this point.

**Comment by thbar** [comment]
I attempted to try running `gcore` to capture a core dump of the running system, but actually:

* The terminal itself is frozen
* Running a different terminal app (I tried `iterm2`) didn't solve it (it was equally frozen)
* Running via SSH doesn't work either

So the system seems to be stuck in a pretty dire state when I try this.

**Comment by jvns** [comment]
@thbar this is extremely interesting thanks!! what a fascinating bug. You weren't running `cargo test` as root, right? Like running the tests as a normal user was enough to freeze the OS?

**Comment by thbar** [comment]
Running as non root, yes! The OS is not completely frozen (I can still browse with Safari) but still fairly frozen.

Envoyé de mon iPhone

**Comment by jvns** [comment]
ideas for places it might make sense to put print statements to try to track this down:

* before/after the call to `task_for_pid` https://github.com/rbspy/rbspy/blob/63cd061ba4085052b8318e2d5b36c9594447d3d2/src/mac_maps.rs#L95
* before/after calling `mach_vm_region` https://github.com/rbspy/rbspy/blob/63cd061ba4085052b8318e2d5b36c9594447d3d2/src/mac_maps.rs#L65 
* before/after calling `copy_address` https://github.com/rbspy/rbspy/blob/63cd061ba4085052b8318e2d5b36c9594447d3d2/src/copy.rs#L45

those 3 things are the only Mac "system call"-like things in the program so my guess is that one of them is causing the system to hang.

**Comment by parkr** [comment]
I added a debugging `println!` before and after each of those 3 calls. I ran `cargo build`. I wrote a simple `program.rb` which contains `puts "hi"`. Then, I ran `RUST_LOG=debug ./target/debug/rbspy record ruby ./program.rb`. It didn't get very far. I saw `Calling mach::traps::task_for_pid` and that's all the output that the program printed before hanging again.

**Comment by jvns** [comment]
@parkr that's really useful, thank you so much! I managed to make a small (< 20 line) C program that reproducibly freezes on my Mac as well: https://gist.github.com/jvns/b721a1a0198c2253779d1850949936d5. (I can't run `ps`, etc)

I think this is a Mac kernel bug -- I think what's going on is if you run `task_for_pid` on a process that you just exec'd (like what rbspy does when you run `rbspy record jekyll build`), then for some reason the computer hangs.

In my experimentation so far, I can fix this pretty easily just by adding a `sleep` of a few milliseconds between starting the subprocess and running `task_for_pid` -- as long as I give the subprocess a second to start before running `task_for_pid` on it everything seems to work fine. So I think we can fix this and make it not freeze folks' computers anymore! This is such a weird and cool bug.

**Comment by jvns** [comment]
Pushed a commit to the `mac-support` branch that adds a 5ms sleep before running `task_for_pid` -- I **think** this should be enough to avoid the race that causes the freeze. (`cargo test` will still fail, need to do more work there, but it at least shouldn't freeze the system now hopefully)

**Comment by tbodt** [comment]
Likely related: https://github.com/hishamhm/htop/issues/682

**Comment by thbar** [comment]
@jvns I tested out with your sleep fix at ce8a99162492b1d4662e81475ff0ce4af3db516d and `cargo test` doesn't lock down my machine anymore. Thanks for the fix!

As bonus questions, I wonder:
* What happens if I start profiling, `task_for_pid` is called, and the profiled program exit right before those 5 ms. I wonder if I'd get the same type of crash?
* Could there be situations where 5 ms is not long enough?

Anyway these are just questions that can probably wait, if this is a kernel bug, maybe it's good enough until they fix it.

Thanks!

**Comment by parkr** [comment]
I pulled, re-compiled, then re-ran `~/code/rbspy/target/debug/rbspy record jekyll build`, and it failed finding the Ruby version. I'm running Ruby 2.5.0 from rbenv 1.1.1 (rbenv installed via Homebrew). It didn't hang!!

However, when I re-ran with `RUST_LOG=debug`, it hung. Which is super weird! I was trying to look through `debug!()` macro calls but nothing really seemed to stick out as the cause. Interesting!!

**Comment by jvns** [comment]
@parkr That's really weird! Can you still reproduce?

**Comment by parkr** [comment]
Things no longer hang for me! 🎉
