### ISSUE TITLE
[mac-support] error while trying to profile

### ISSUE THREAD

**Issue by thbar** [rbspy/rbspy#76]
Hello again :smile: I tried using the `mac-support` branch but cannot get to profile a program.

I'm using this very simple program, with RVM 1.29.3 and Ruby 2.5.0.

```ruby
loop do
  sleep(0.2)
  puts "OK"
end
```

I then get the pid and run:

```
✘-1 ~/git/kiba-ruby-benchmarks [master|✚ 1…1] 
19:21 $ sudo ../rbspy/target/debug/rbspy record --pid 7185
Error. Causes: 
- Couldn't determine Ruby version
- Couldn't get `_ruby_version` symbol. This is likely because rbspy doesn't work with system Ruby on Mac. Try with rbenv/rvm ruby?
```

**Comment by thbar** [comment]
I noticed that `ruby-bindings/src` does not contain `ruby_2_5_0.rs` (only `ruby_2_5_0_rc1.rs`), so I made a test with another ruby appearing in that folder (2.4.3), but the problem is the same.

**Comment by jvns** [comment]
@thbar thanks! How did you install the Ruby you're using? Can you run `nm` on the Ruby binary you're using and paste the output?

**Comment by segiddins** [comment]
```
$ target/debug/rbspy record -- ruby -e 'def s; sleep(2); p(:true); end; s; s'

Error. Causes:
- Couldn't determine Ruby version
- Couldn't get port for PID 78932. Possibilities: that process doesn't exist, you need to be root, or you have SIP enabled and you're trying to profile system Ruby (try rbenv instead).
```

I use `chruby`, so the `ruby` executable on my `$PATH` is definitely not system ruby

**Comment by jvns** [comment]
@segiddins are you running that command as root? in any case I'm seeing that this error message definitely needs to be more specific about the issue =) (instead of saying "it's X or Y or Z")

**Comment by thbar** [comment]
@jvns it was installed via RVM 1.29.3. Here is the output for `nm` - it looks very short and there is no trace of `ruby_version` in there!

```
$ nm /Users/thbar/.rvm/rubies/ruby-2.5.0/bin/ruby
0000000100000000 T __mh_execute_header
0000000100000ee0 t _main
                 U _ruby_init
                 U _ruby_init_stack
                 U _ruby_options
                 U _ruby_run_node
                 U _ruby_sysinit
                 U _setlocale
                 U dyld_stub_binder
```

This is running via my regular non-root user.

**Comment by segiddins** [comment]
No, not running it as root, since the README said root was only needed when passing in an existing PID

**Comment by thbar** [comment]
FWIW, all the `ruby` I tested (2.2.6, 2.4.0, 2.5.0) show an equally short output for `nm`.

If you give me more instructions, I can definitely run more testing.

**Comment by jvns** [comment]
thanks that's helpful! What I'm learning from this is that the way `rbenv` installs Ruby is different from `rvm` and that I should test both.

**Comment by jvns** [comment]
@segiddins yeah sorry -- the README directions won't be true for Mac, for Mac you need to run rbspy as root no matter what. Will update the README in the branch.

**Comment by segiddins** [comment]
> for Mac you need to run rbspy as root no matter what

uh oh... that may cause issues when trying to profile anything that uses Bundler :/

Is that a limitation we could work around?

**Comment by jvns** [comment]
@segiddins yeah I think so! My plan is to make rbspy by default drop root privileges when it execs a subprocess, so you can run `sudo -e rbspy bundle ...` and then when rbspy starts bundler it'll start it as your user, not root. The `-e` will be required so that `sudo` keeps all your normal environment variables.

Do you think that will work?

**Comment by segiddins** [comment]
> Do you think that will work?

Maybe! Alternatively, and this would require some more work, would be to allow running `rbspy` as my normal user, and if necessary it will `sudo` itself (I guess just `exec`ing itself)? Because remembering flags is hard.

Also, `sudo -e` seems to be for editing files, I think you meant `sudo -E`?

**Comment by segiddins** [comment]
```
$ sudo -E target/debug/rbspy record -- ruby -e 'def s; sleep(2); p(:true);

Recording data to /Users/segiddins/.cache/rbspy/records/rbspy-2018-01-29-MxG6wl6fao.txt
Press Ctrl+C to stop
Dropped 21/21 stack traces because of errors.
Error. Causes:
- Failed to copy memory address 8
- Operation timed out (os error 60)
```

**Comment by jvns** [comment]
just execing itself with sudo is good idea, thanks! I do mean `sudo -E`.

I'm going to do a bunch of work on Mac rbspy this afternoon (including investigating some of these errors you're reporting) and come back with a bunch of improvements!

**Comment by jvns** [comment]
out of curiosity -- have you tried using stackprof to profile Bundler?

**Comment by segiddins** [comment]
> out of curiosity -- have you tried using stackprof to profile Bundler?

I've used `rubyprof` in the past, but I don't love its output options, and it makes running things so slow, I can't really use it for meaningful iteration (i.e. "does this change make bundler faster"). I've never used `stackprof`

**Comment by jvns** [comment]
I think these errors should be sorted out on the current mac support branch (@segiddins reported success on Twitter) so I'm going to close this for now. feel free to reopen!
