### ISSUE TITLE
Make rbspy on Mac use goblin instead of nm

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#81]
Parsing the output of `nm` to get symbol addresses on Mac doesn't seem that robust (what if people don't have `nm` installed?).

The specific issue I ran into with goblin was that goblin didn't parse the symbols from the libruby dylib from rvm properly (it reported the symbol value for the `ruby_version` as 0 instead of the actual symbol value). Need to report this issue to goblin and ideally contribute a fix.

**Comment by indirect** [comment]
fwiw, `nm` comes with XCode! so developers on OS X should have `nm` installed. 👍 

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm
```

**Comment by jvns** [comment]
oh cool! in that case I'll close because I don't think using nm is negatively affecting anyone :)
