### ISSUE TITLE
`-V` shouldn't require root

### ISSUE THREAD

**Issue by jacobbednarz** [rbspy/rbspy#88]
Whilst putting together the Homebrew formula for this package (in Homebrew/homebrew-core#23575) I noticed that `rbspy -V` requires root permissions despite (on the surface) not needing these elevated permissions. Is this by design and I'm missing something here? Or should it not worry about needing root when calling this?

**Comment by jvns** [comment]
yep, this is a bug. thanks for the report!

also it probably makes more sense to package rbspy 0.1.8 for homebrew since that's the latest version as of this morning (0.1.8 has a fix which makes it less likely to freeze your mac :))

**Comment by jacobbednarz** [comment]
> also it probably makes more sense to package rbspy 0.1.8 for homebrew since that's the latest version as of this morning

I made the ol' copy/pasta fail from the first PR 😛 (title + commit message said 0.1.7 but formula was 0.1.8)

**Comment by jacobbednarz** [comment]
Wow, such speed!
