### ISSUE TITLE
Alternative time viewing formats

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rbspy/rbspy#92]
I see in this blog post you're looking at ways to view times for call graphs
https://jvns.ca/blog/2018/02/06/profiler-week-5/

Including (I imagine) total time for a function (including time of all functions called) and time spent in the code of that function itself, including for recursive programs.

You might want to look at some of the tools Android has for this which allow you to navigate an ordered list (by % of time spent) of functions, and down into their children (which recursively might lead you back to the original :-) )...

I don't have a screenshot handy, but as it's interactive you might want to play with it anyway.... If you need pointers to blog posts of videos, I can find them (don't have my Android environment up to date :-( ).

If you generate output in a suitable format, you might even be able to use the tool directly, it's all written in portable Java I think.

(BTW: They have Memory profiling analysis tools also, with "retained memory" and the like also....)

**Comment by jvns** [comment]
Definitely have plans for this kind of total time / self time summary output format. If you wanted to contribute it, it'd be fairly simple to do -- the definitions for the flamegraph & callgrind formats are in https://github.com/rbspy/rbspy/blob/master/src/output.rs

One thing that I want to work out is how to let people easily decide to postprocess raw profiler data in different formats. Could be good to develop a simple "raw" format (maybe just the format flamegraph.pl uses), and add a `postprocess` subcommand that lets you later transform that raw data into any format you want. (flamegraph / summary / callgrind etc).

**Comment by jvns** [comment]
this is done!
